/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ArchivingGetStatisticsResponseStatisticByFileStatus
 */
public class ArchivingGetStatisticsResponseStatisticByFileStatusTest {
    private final ArchivingGetStatisticsResponseStatisticByFileStatus model = new ArchivingGetStatisticsResponseStatisticByFileStatus();

    /**
     * Model tests for ArchivingGetStatisticsResponseStatisticByFileStatus
     */
    @Test
    public void testArchivingGetStatisticsResponseStatisticByFileStatus() {
        // TODO: test ArchivingGetStatisticsResponseStatisticByFileStatus
    }

    /**
     * Test the property 'processingFileCount'
     */
    @Test
    public void processingFileCountTest() {
        // TODO: test processingFileCount
    }

    /**
     * Test the property 'completedFileCount'
     */
    @Test
    public void completedFileCountTest() {
        // TODO: test completedFileCount
    }

    /**
     * Test the property 'failedFileCount'
     */
    @Test
    public void failedFileCountTest() {
        // TODO: test failedFileCount
    }

}
