/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DevicesChangeDeviceAssociationRequest
 */
public class DevicesChangeDeviceAssociationRequestTest {
    private final DevicesChangeDeviceAssociationRequest model = new DevicesChangeDeviceAssociationRequest();

    /**
     * Model tests for DevicesChangeDeviceAssociationRequest
     */
    @Test
    public void testDevicesChangeDeviceAssociationRequest() {
        // TODO: test DevicesChangeDeviceAssociationRequest
    }

    /**
     * Test the property 'roomId'
     */
    @Test
    public void roomIdTest() {
        // TODO: test roomId
    }

    /**
     * Test the property 'appType'
     */
    @Test
    public void appTypeTest() {
        // TODO: test appType
    }

}
