/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingAndWebinarPollingObject1QuestionsInnerPromptsInner
 */
public class MeetingAndWebinarPollingObject1QuestionsInnerPromptsInnerTest {
    private final MeetingAndWebinarPollingObject1QuestionsInnerPromptsInner model = new MeetingAndWebinarPollingObject1QuestionsInnerPromptsInner();

    /**
     * Model tests for MeetingAndWebinarPollingObject1QuestionsInnerPromptsInner
     */
    @Test
    public void testMeetingAndWebinarPollingObject1QuestionsInnerPromptsInner() {
        // TODO: test MeetingAndWebinarPollingObject1QuestionsInnerPromptsInner
    }

    /**
     * Test the property 'promptQuestion'
     */
    @Test
    public void promptQuestionTest() {
        // TODO: test promptQuestion
    }

    /**
     * Test the property 'promptRightAnswers'
     */
    @Test
    public void promptRightAnswersTest() {
        // TODO: test promptRightAnswers
    }

}
