/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MeetingsCreateBatchPollsRequestPollsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsCreateBatchPollsRequest
 */
public class MeetingsCreateBatchPollsRequestTest {
    private final MeetingsCreateBatchPollsRequest model = new MeetingsCreateBatchPollsRequest();

    /**
     * Model tests for MeetingsCreateBatchPollsRequest
     */
    @Test
    public void testMeetingsCreateBatchPollsRequest() {
        // TODO: test MeetingsCreateBatchPollsRequest
    }

    /**
     * Test the property 'polls'
     */
    @Test
    public void pollsTest() {
        // TODO: test polls
    }

}
