/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MeetingsCreateBatchPollsResponsePollsInnerQuestionsInnerPromptsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsCreateBatchPollsResponsePollsInnerQuestionsInner
 */
public class MeetingsCreateBatchPollsResponsePollsInnerQuestionsInnerTest {
    private final MeetingsCreateBatchPollsResponsePollsInnerQuestionsInner model = new MeetingsCreateBatchPollsResponsePollsInnerQuestionsInner();

    /**
     * Model tests for MeetingsCreateBatchPollsResponsePollsInnerQuestionsInner
     */
    @Test
    public void testMeetingsCreateBatchPollsResponsePollsInnerQuestionsInner() {
        // TODO: test MeetingsCreateBatchPollsResponsePollsInnerQuestionsInner
    }

    /**
     * Test the property 'answerMaxCharacter'
     */
    @Test
    public void answerMaxCharacterTest() {
        // TODO: test answerMaxCharacter
    }

    /**
     * Test the property 'answerMinCharacter'
     */
    @Test
    public void answerMinCharacterTest() {
        // TODO: test answerMinCharacter
    }

    /**
     * Test the property 'answerRequired'
     */
    @Test
    public void answerRequiredTest() {
        // TODO: test answerRequired
    }

    /**
     * Test the property 'answers'
     */
    @Test
    public void answersTest() {
        // TODO: test answers
    }

    /**
     * Test the property 'caseSensitive'
     */
    @Test
    public void caseSensitiveTest() {
        // TODO: test caseSensitive
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'prompts'
     */
    @Test
    public void promptsTest() {
        // TODO: test prompts
    }

    /**
     * Test the property 'ratingMaxLabel'
     */
    @Test
    public void ratingMaxLabelTest() {
        // TODO: test ratingMaxLabel
    }

    /**
     * Test the property 'ratingMaxValue'
     */
    @Test
    public void ratingMaxValueTest() {
        // TODO: test ratingMaxValue
    }

    /**
     * Test the property 'ratingMinLabel'
     */
    @Test
    public void ratingMinLabelTest() {
        // TODO: test ratingMinLabel
    }

    /**
     * Test the property 'ratingMinValue'
     */
    @Test
    public void ratingMinValueTest() {
        // TODO: test ratingMinValue
    }

    /**
     * Test the property 'rightAnswers'
     */
    @Test
    public void rightAnswersTest() {
        // TODO: test rightAnswers
    }

    /**
     * Test the property 'showAsDropdown'
     */
    @Test
    public void showAsDropdownTest() {
        // TODO: test showAsDropdown
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
