/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions
 */
public class MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegionsTest {
    private final MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions model = new MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions();

    /**
     * Model tests for MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    @Test
    public void testMeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions() {
        // TODO: test MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions
    }

    /**
     * Test the property 'approvedList'
     */
    @Test
    public void approvedListTest() {
        // TODO: test approvedList
    }

    /**
     * Test the property 'deniedList'
     */
    @Test
    public void deniedListTest() {
        // TODO: test deniedList
    }

    /**
     * Test the property 'enable'
     */
    @Test
    public void enableTest() {
        // TODO: test enable
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

}
