/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsCreateMeetingResponseSettingsResourcesInner
 */
public class MeetingsCreateMeetingResponseSettingsResourcesInnerTest {
    private final MeetingsCreateMeetingResponseSettingsResourcesInner model = new MeetingsCreateMeetingResponseSettingsResourcesInner();

    /**
     * Model tests for MeetingsCreateMeetingResponseSettingsResourcesInner
     */
    @Test
    public void testMeetingsCreateMeetingResponseSettingsResourcesInner() {
        // TODO: test MeetingsCreateMeetingResponseSettingsResourcesInner
    }

    /**
     * Test the property 'resourceType'
     */
    @Test
    public void resourceTypeTest() {
        // TODO: test resourceType
    }

    /**
     * Test the property 'resourceId'
     */
    @Test
    public void resourceIdTest() {
        // TODO: test resourceId
    }

    /**
     * Test the property 'permissionLevel'
     */
    @Test
    public void permissionLevelTest() {
        // TODO: test permissionLevel
    }

}
