/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner
 */
public class MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInnerTest {
    private final MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner model = new MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner();

    /**
     * Model tests for MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner
     */
    @Test
    public void testMeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner() {
        // TODO: test MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
