/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsListMeetingSummariesResponseSummariesInner
 */
public class MeetingsListMeetingSummariesResponseSummariesInnerTest {
    private final MeetingsListMeetingSummariesResponseSummariesInner model = new MeetingsListMeetingSummariesResponseSummariesInner();

    /**
     * Model tests for MeetingsListMeetingSummariesResponseSummariesInner
     */
    @Test
    public void testMeetingsListMeetingSummariesResponseSummariesInner() {
        // TODO: test MeetingsListMeetingSummariesResponseSummariesInner
    }

    /**
     * Test the property 'meetingHostId'
     */
    @Test
    public void meetingHostIdTest() {
        // TODO: test meetingHostId
    }

    /**
     * Test the property 'meetingHostEmail'
     */
    @Test
    public void meetingHostEmailTest() {
        // TODO: test meetingHostEmail
    }

    /**
     * Test the property 'meetingUuid'
     */
    @Test
    public void meetingUuidTest() {
        // TODO: test meetingUuid
    }

    /**
     * Test the property 'meetingId'
     */
    @Test
    public void meetingIdTest() {
        // TODO: test meetingId
    }

    /**
     * Test the property 'meetingTopic'
     */
    @Test
    public void meetingTopicTest() {
        // TODO: test meetingTopic
    }

    /**
     * Test the property 'meetingStartTime'
     */
    @Test
    public void meetingStartTimeTest() {
        // TODO: test meetingStartTime
    }

    /**
     * Test the property 'meetingEndTime'
     */
    @Test
    public void meetingEndTimeTest() {
        // TODO: test meetingEndTime
    }

    /**
     * Test the property 'summaryStartTime'
     */
    @Test
    public void summaryStartTimeTest() {
        // TODO: test summaryStartTime
    }

    /**
     * Test the property 'summaryEndTime'
     */
    @Test
    public void summaryEndTimeTest() {
        // TODO: test summaryEndTime
    }

    /**
     * Test the property 'summaryCreatedTime'
     */
    @Test
    public void summaryCreatedTimeTest() {
        // TODO: test summaryCreatedTime
    }

    /**
     * Test the property 'summaryLastModifiedTime'
     */
    @Test
    public void summaryLastModifiedTimeTest() {
        // TODO: test summaryLastModifiedTime
    }

}
