/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsGetMeetingSummaryResponseSummaryDetailsInner
 */
public class MeetingsGetMeetingSummaryResponseSummaryDetailsInnerTest {
    private final MeetingsGetMeetingSummaryResponseSummaryDetailsInner model = new MeetingsGetMeetingSummaryResponseSummaryDetailsInner();

    /**
     * Model tests for MeetingsGetMeetingSummaryResponseSummaryDetailsInner
     */
    @Test
    public void testMeetingsGetMeetingSummaryResponseSummaryDetailsInner() {
        // TODO: test MeetingsGetMeetingSummaryResponseSummaryDetailsInner
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

}
