/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsGetJoinTokenLocalRecordingResponse
 */
public class MeetingsGetJoinTokenLocalRecordingResponseTest {
    private final MeetingsGetJoinTokenLocalRecordingResponse model = new MeetingsGetJoinTokenLocalRecordingResponse();

    /**
     * Model tests for MeetingsGetJoinTokenLocalRecordingResponse
     */
    @Test
    public void testMeetingsGetJoinTokenLocalRecordingResponse() {
        // TODO: test MeetingsGetJoinTokenLocalRecordingResponse
    }

    /**
     * Test the property 'expireIn'
     */
    @Test
    public void expireInTest() {
        // TODO: test expireIn
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

}
