/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeetingsCreateInviteLinksResponseAttendeesInner
 */
public class MeetingsCreateInviteLinksResponseAttendeesInnerTest {
    private final MeetingsCreateInviteLinksResponseAttendeesInner model = new MeetingsCreateInviteLinksResponseAttendeesInner();

    /**
     * Model tests for MeetingsCreateInviteLinksResponseAttendeesInner
     */
    @Test
    public void testMeetingsCreateInviteLinksResponseAttendeesInner() {
        // TODO: test MeetingsCreateInviteLinksResponseAttendeesInner
    }

    /**
     * Test the property 'joinUrl'
     */
    @Test
    public void joinUrlTest() {
        // TODO: test joinUrl
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
