/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ReportsGetTelephoneReportsResponseTelephonyUsageInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportsGetTelephoneReportsResponse
 */
public class ReportsGetTelephoneReportsResponseTest {
    private final ReportsGetTelephoneReportsResponse model = new ReportsGetTelephoneReportsResponse();

    /**
     * Model tests for ReportsGetTelephoneReportsResponse
     */
    @Test
    public void testReportsGetTelephoneReportsResponse() {
        // TODO: test ReportsGetTelephoneReportsResponse
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

    /**
     * Test the property 'pageCount'
     */
    @Test
    public void pageCountTest() {
        // TODO: test pageCount
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'totalRecords'
     */
    @Test
    public void totalRecordsTest() {
        // TODO: test totalRecords
    }

    /**
     * Test the property 'telephonyUsage'
     */
    @Test
    public void telephonyUsageTest() {
        // TODO: test telephonyUsage
    }

}
