/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportsWebinarParticipantsListResponseParticipantsInner
 */
public class ReportsWebinarParticipantsListResponseParticipantsInnerTest {
    private final ReportsWebinarParticipantsListResponseParticipantsInner model = new ReportsWebinarParticipantsListResponseParticipantsInner();

    /**
     * Model tests for ReportsWebinarParticipantsListResponseParticipantsInner
     */
    @Test
    public void testReportsWebinarParticipantsListResponseParticipantsInner() {
        // TODO: test ReportsWebinarParticipantsListResponseParticipantsInner
    }

    /**
     * Test the property 'customerKey'
     */
    @Test
    public void customerKeyTest() {
        // TODO: test customerKey
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'failover'
     */
    @Test
    public void failoverTest() {
        // TODO: test failover
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'joinTime'
     */
    @Test
    public void joinTimeTest() {
        // TODO: test joinTime
    }

    /**
     * Test the property 'leaveTime'
     */
    @Test
    public void leaveTimeTest() {
        // TODO: test leaveTime
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'registrantId'
     */
    @Test
    public void registrantIdTest() {
        // TODO: test registrantId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'userEmail'
     */
    @Test
    public void userEmailTest() {
        // TODO: test userEmail
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'participantUserId'
     */
    @Test
    public void participantUserIdTest() {
        // TODO: test participantUserId
    }

}
