/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TspAddUserTspAccountResponseDialInNumbersInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TspAddUserTspAccountResponse
 */
public class TspAddUserTspAccountResponseTest {
    private final TspAddUserTspAccountResponse model = new TspAddUserTspAccountResponse();

    /**
     * Model tests for TspAddUserTspAccountResponse
     */
    @Test
    public void testTspAddUserTspAccountResponse() {
        // TODO: test TspAddUserTspAccountResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'conferenceCode'
     */
    @Test
    public void conferenceCodeTest() {
        // TODO: test conferenceCode
    }

    /**
     * Test the property 'dialInNumbers'
     */
    @Test
    public void dialInNumbersTest() {
        // TODO: test dialInNumbers
    }

    /**
     * Test the property 'leaderPin'
     */
    @Test
    public void leaderPinTest() {
        // TODO: test leaderPin
    }

    /**
     * Test the property 'tspBridge'
     */
    @Test
    public void tspBridgeTest() {
        // TODO: test tspBridge
    }

}
