/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WebinarsListPollResultsResponseQuestionsInnerQuestionDetailsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebinarsListPollResultsResponseQuestionsInner
 */
public class WebinarsListPollResultsResponseQuestionsInnerTest {
    private final WebinarsListPollResultsResponseQuestionsInner model = new WebinarsListPollResultsResponseQuestionsInner();

    /**
     * Model tests for WebinarsListPollResultsResponseQuestionsInner
     */
    @Test
    public void testWebinarsListPollResultsResponseQuestionsInner() {
        // TODO: test WebinarsListPollResultsResponseQuestionsInner
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'questionDetails'
     */
    @Test
    public void questionDetailsTest() {
        // TODO: test questionDetails
    }

}
