/*
 * Zoom Meeting API
 * The Zoom Meeting APIs let developers to access information from Zoom. 
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebinarsUpdateLiveStreamRequest
 */
public class WebinarsUpdateLiveStreamRequestTest {
    private final WebinarsUpdateLiveStreamRequest model = new WebinarsUpdateLiveStreamRequest();

    /**
     * Model tests for WebinarsUpdateLiveStreamRequest
     */
    @Test
    public void testWebinarsUpdateLiveStreamRequest() {
        // TODO: test WebinarsUpdateLiveStreamRequest
    }

    /**
     * Test the property 'pageUrl'
     */
    @Test
    public void pageUrlTest() {
        // TODO: test pageUrl
    }

    /**
     * Test the property 'streamKey'
     */
    @Test
    public void streamKeyTest() {
        // TODO: test streamKey
    }

    /**
     * Test the property 'streamUrl'
     */
    @Test
    public void streamUrlTest() {
        // TODO: test streamUrl
    }

    /**
     * Test the property 'resolution'
     */
    @Test
    public void resolutionTest() {
        // TODO: test resolution
    }

}
