openapi: 3.0.0
info:
  contact:
    name: Zoom Developers
    url: https://developer.zoom.us/
  description: 'The Zoom Meeting APIs let developers to access information from Zoom. '
  termsOfService: https://zoom.us/docs/en-us/zoom_api_license_and_tou.html
  title: Zoom Meeting API
  version: "2"
  x-konfig-ignore:
    object-with-no-properties: true
    potential-incorrect-type: true
  x-konfig-has-globally-required-security: true
  x-konfig-uses-multipart-form-data: true
servers:
- url: https://api.zoom.us/v2
tags:
- name: Webinars
- name: Meetings
- name: Reports
- name: Cloud Recording
- name: Devices
- name: TSP
- name: Archiving
- name: Tracking Field
- name: H323 Devices
- name: SIP Phone
- name: PAC
paths:
  /archive_files:
    get:
      description: "Get an account's archived meeting or webinar files. \n\n Zoom's\
        \ [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators)\
        \ lets account administrators set up an automated mechanism to record, collect,\
        \ and archive meeting data to a third-party platform of their choice to satisfy\
        \ FINRA or other compliance requirements. \n\n **Prerequisites:** \n* The\
        \ [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)\
        \ enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003).\n\
        \n**Scopes:** `recording:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Archiving_meetingFilesList
      security:
      - openapi_oauth:
        - recording:read:admin
        openapi_authorization: []
      summary: List archived files
      tags:
      - Archiving
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--archive_files
      x-accepts: application/json
  /archive_files/statistics:
    get:
      description: "Get statistics about an account's archived meeting or webinar\
        \ files. \n\n Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators)\
        \ lets account administrators set up an automated mechanism to record, collect,\
        \ and archive meeting data to a third-party platform of their choice to satisfy\
        \ FINRA and other compliance requirements. \n\n **Prerequisites:** \n* The\
        \ [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)\
        \ enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003).\n\
        \n**Scopes:** `recording:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Archiving_getStatistics
      security:
      - openapi_oauth:
        - recording:read:admin
        openapi_authorization: []
      summary: Get archived file statistics
      tags:
      - Archiving
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--archive_files-statistics
      x-accepts: application/json
  /archive_files/{fileId}:
    patch:
      description: "Update an archived file's auto-delete status. \n\n **Prerequisites:**\
        \ \n* [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003)\
        \ must enable the [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)\
        \ for your account.\n* Open the disabling auto-delete feature in OP. Contact\
        \ [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to open.\n\
        \n**Scopes:** `recording:write`,`recording:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Archiving_updateAutoDeleteStatus
      security:
      - openapi_oauth:
        - recording:write
        - recording:write:admin
        openapi_authorization: []
      summary: Update an archived file's auto-delete status
      tags:
      - Archiving
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--archive_files-fileId
      x-content-type: application/json
      x-accepts: application/json
  /past_meetings/{meetingUUID}/archive_files:
    delete:
      description: "Use this API to delete all of a meeting's archived files. \n\n\
        \ **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)\
        \ enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003).\n\
        \n**Scopes:** `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Archiving_meetingFilesDelete
      security:
      - openapi_oauth:
        - recording:write:admin
        - recording:write
        openapi_authorization: []
      summary: Delete a meeting's archived files
      tags:
      - Archiving
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--past_meetings-meetingUUID-archive_files
      x-accepts: application/json
    get:
      description: "Return a specific meeting instance's [archived files](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators).\
        \ \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)\
        \ enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003).\n\
        \n**Scopes:** `recording:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Archiving_meetingFilesList
      security:
      - openapi_oauth:
        - recording:read
        openapi_authorization: []
      summary: Get a meeting's archived files
      tags:
      - Archiving
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_meetings-meetingUUID-archive_files
      x-accepts: application/json
  /meetings/{meetingId}/recordings:
    delete:
      description: "Delete all recording files of a meeting.  \n   \n\n \n\n**Prerequisites**:\n\
        * Cloud Recording should be enabled on the user's account.  \n \n\n\n**Scopes:**\
        \ `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: CloudRecording_deleteMeetingRecordings
      security:
      - openapi_oauth:
        - recording:write:admin
        - recording:write
        openapi_authorization: []
      summary: Delete meeting recordings
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--meetings-meetingId-recordings
      x-accepts: application/json
    get:
      description: "Returns all of a meeting's [recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording#h_7420acb5-1897-4061-87b4-5b76e99c03b4).\n\
        \n Use the `download_url` property listed in the response to download the\
        \ recording files.  To access a passcode-protected cloud recording, send the\
        \ user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/)\
        \ as a Bearer token in the Authorization header. \n \n Example:  `curl -H\
        \ 'Authorization: Bearer <ACCESS_TOKEN>' https://{{base-domain}}/rec/archive/download/xyz`\
        \  \n\n**Scopes:** `recording:read`,`phone_recording:read:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: CloudRecording_getMeetingRecordings
      security:
      - openapi_oauth:
        - recording:read
        - phone_recording:read:admin
        openapi_authorization: []
      summary: Get meeting recordings
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-recordings
      x-accepts: application/json
  /meetings/{meetingId}/recordings/analytics_details:
    get:
      description: "Use this API to return a meeting recording's [analytics details](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163).\
        \ **Maximum duration: 1 Month**. To access a password-protected cloud recording,\
        \ send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/)\
        \ as a Bearer token in the Authorization header. For example, \n\n `curl -H\
        \ &quot;Authorization: Bearer &lt;ACCESS_TOKEN&gt;&quot; https://{{base-domain}}/rec/archive/download/xyz`\
        \ \n\n\n \n\n**Scopes:** `recording:read:admin`,`recording:read`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: analytics_details
      security:
      - openapi_oauth:
        - recording:read:admin
        - recording:read
        openapi_authorization: []
      summary: Get Meeting Recording's Analytics Details
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-recordings-analytics_details
      x-accepts: application/json
  /meetings/{meetingId}/recordings/analytics_summary:
    get:
      description: "Use this API to return a meeting recording's [analytics summary](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163).\
        \ **Maximum duration: 1 Month**. To access a password-protected cloud recording,\
        \ send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/)\
        \ as a Bearer token in the Authorization header. For example, \n\n `curl -H\
        \ &quot;Authorization: Bearer &lt;ACCESS_TOKEN&gt;&quot; https://{{base-domain}}/rec/archive/download/xyz`\
        \ \n\n\n \n\n**Scopes:** `recording:read:admin`,`recording:read`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: analytics_summary
      security:
      - openapi_oauth:
        - recording:read:admin
        - recording:read
        openapi_authorization: []
      summary: Get Meeting Recording's Analytics Summary
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-recordings-analytics_summary
      x-accepts: application/json
  /meetings/{meetingId}/recordings/registrants:
    get:
      description: "Use this API to list registrants of a past meeting's [on-demand\
        \ cloud recordings](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-recordings).\
        \ Users must [register](https://developers.zoom.us) to view the recordings.\
        \ \n\n \n\n**Scopes:** `recording:read:admin`,`recording:read`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: CloudRecording_listRegistrants
      security:
      - openapi_oauth:
        - recording:read:admin
        - recording:read
        openapi_authorization: []
      summary: List recording registrants
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-recordings-registrants
      x-accepts: application/json
    post:
      description: "Cloud Recordings of past Zoom Meetings can be made [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings).\
        \ Users should be [registered](https://developers.zoom.us) to view these recordings.\n\
        \nUse this API to register a user to gain access to **On-demand Cloud Recordings**\
        \ of a past meeting.  \n \n\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: CloudRecording_createRegistrant
      security:
      - openapi_oauth:
        - recording:write:admin
        - recording:write
        openapi_authorization: []
      summary: Create a recording registrant
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--meetings-meetingId-recordings-registrants
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/recordings/registrants/questions:
    get:
      description: "For [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings)\
        \ meeting recordings, you can include fields with questions that will be shown\
        \ to registrants when they register to view the recording.\n\nUse this API\
        \ to retrieve a list of questions that are displayed for users to complete\
        \ when registering to view the recording of a specific meeting.  \n \n\n\n\
        **Scopes:** `recording:read:admin`,`recording:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: CloudRecording_listRegistrationQuestions
      security:
      - openapi_oauth:
        - recording:read:admin
        - recording:read
        openapi_authorization: []
      summary: Get registration questions
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-recordings-registrants-questions
      x-accepts: application/json
    patch:
      description: "For [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings)\
        \ meeting recordings, you can include fields with questions that will be shown\
        \ to registrants when they register to view the recording.\n\nUse this API\
        \ to update registration questions that are to be answered by users while\
        \ registering to view a recording.  \n \n\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: CloudRecording_updateRegistrationQuestions
      security:
      - openapi_oauth:
        - recording:write:admin
        - recording:write
        openapi_authorization: []
      summary: Update registration questions
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--meetings-meetingId-recordings-registrants-questions
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/recordings/registrants/status:
    put:
      description: "A registrant can either be approved or denied from viewing the\
        \ [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings)\
        \ recording. \nUse this API to update a registrant's status.\n\n\n\n**Scopes:**\
        \ `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: CloudRecording_updateRegistrantStatus
      security:
      - openapi_oauth:
        - recording:write:admin
        - recording:write
        openapi_authorization: []
      summary: Update registrant's status
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--meetings-meetingId-recordings-registrants-status
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/recordings/settings:
    get:
      description: "Retrieves settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).\
        \  \n   \n\n \n\n\n**Scopes:** `recording:read:admin`,`recording:read`\n\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: CloudRecording_getSettings
      security:
      - openapi_oauth:
        - recording:read:admin
        - recording:read
        openapi_authorization: []
      summary: Get meeting recording settings
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-recordings-settings
      x-accepts: application/json
    patch:
      description: "Updates settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).\
        \      \n\n**Scopes:** `recording:write`,`recording:write:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: CloudRecording_updateSettings
      security:
      - openapi_oauth:
        - recording:write
        - recording:write:admin
        openapi_authorization: []
      summary: Update meeting recording settings
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--meetings-meetingId-recordings-settings
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/recordings/{recordingId}:
    delete:
      description: |-
        Delete a specific recording file from a meeting.&lt;p style=&quot;background-color:#e1f5fe; color:#01579b; padding:8px&quot;&gt; &lt;b&gt;Note:&lt;/b&gt; To use this API, you must enable the &lt;b&gt;The host can delete cloud recordings&lt;/b&gt; setting. You can find this setting in the &lt;b&gt;Recording&lt;/b&gt; tab of the &lt;b&gt;Settings&lt;/b&gt; interface in the [Zoom web portal](https://zoom.us/).&lt;/p&gt;



        **Scopes:** `recording:write:admin`,`recording:write`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: CloudRecording_deleteRecording
      security:
      - openapi_oauth:
        - recording:write:admin
        - recording:write
        openapi_authorization: []
      summary: Delete a meeting recording file
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--meetings-meetingId-recordings-recordingId
      x-accepts: application/json
  /meetings/{meetingId}/recordings/{recordingId}/status:
    put:
      description: "Zoom allows users to recover recordings from trash for up to 30\
        \ days from the deletion date. Use this API to recover a single recording\
        \ file from the meeting.  \n \n\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: CloudRecording_recoverStatus
      security:
      - openapi_oauth:
        - recording:write:admin
        - recording:write
        openapi_authorization: []
      summary: Recover a single recording
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--meetings-meetingId-recordings-recordingId-status
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingUUID}/recordings/status:
    put:
      description: "Zoom allows users to recover recordings from trash for up to 30\
        \ days from the deletion date. Use this API to recover all deleted [Cloud\
        \ Recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording)\
        \ of a specific meeting.  \n   \n\n \n**Prerequisites**:  \n \n* A Pro user\
        \ with Cloud Recording enabled.\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: CloudRecording_recoverRecordingStatus
      security:
      - openapi_oauth:
        - recording:write:admin
        - recording:write
        openapi_authorization: []
      summary: Recover meeting recordings
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--meetings-meetingUUID-recordings-status
      x-content-type: application/json
      x-accepts: application/json
  /users/{userId}/recordings:
    get:
      description: "Lists all [cloud recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording)\
        \ for a user.  \n\nFor user-level apps, pass the [`me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)\
        \ instead of the `userId` parameter.  To access a user's passcode protected\
        \ cloud recording, send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/)\
        \ as a bearer token in the authorization header.  \n\nExample:  `curl -H \"\
        Authorization: Bearer <ACCESS_TOKEN>\" https://{{base-domain}}/rec/archive/download/xyz`\
        \  \n\n**Prerequisites:**  \n* Must have a Pro or a higher plan.  \n* Must\
        \ enable Cloud Recording on the user's account.\n\n**Scopes:** `recording:read:admin`,`recording:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: CloudRecording_listRecordings
      security:
      - openapi_oauth:
        - recording:read:admin
        - recording:read
        openapi_authorization: []
      summary: List all recordings
      tags:
      - Cloud Recording
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-recordings
      x-accepts: application/json
  /devices:
    get:
      description: "This API lets you list devices. \n\n\n\n**Scopes:** `device:read:admin`,`device:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Devices_list
      security:
      - openapi_oauth:
        - device:read:admin
        - device:write:admin
        openapi_authorization: []
      summary: List devices
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--devices
      x-accepts: application/json
    post:
      description: "Add a new device to Zoom account. \n\n**Scope:** `device:write:admin`\
        \   \n \n **[Rate Limit Label](https://developers.zoom.us/docs/api/rest/rate-limits/):**\
        \ `Medium`\n\n**Scopes:** `device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Devices_createNewDevice
      security:
      - openapi_oauth:
        - device:write:admin
        openapi_authorization: []
      summary: Add a new device
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--devices
      x-content-type: application/json
      x-accepts: application/json
  /devices/groups:
    get:
      description: |-
        Get Zoom Device Manager (ZDM) group information for an account.

        **Scopes:** `device:read:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`
      operationId: Devices_listZdmGroupInfo
      security:
      - openapi_oauth:
        - device:read:admin
        openapi_authorization: []
      summary: Get zdm group info
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--devices-groups
      x-accepts: application/json
  /devices/zpa/assignment:
    post:
      description: |-
        Assign a device to a user or common area, or move a device to another user or common area, or remove a device.

        **Prerequisites:**
        * Device must be enrolled in Zoom Device Management (ZDM).

        **Scopes:** `device:write:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`
      operationId: Devices_assignDeviceZpaAssignment
      security:
      - openapi_oauth:
        - device:write:admin
        openapi_authorization: []
      summary: Assign a device to a user or commonarea
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--devices-zpa-assignment
      x-content-type: application/json
      x-accepts: application/json
  /devices/zpa/upgrade:
    post:
      description: |-
        Upgrade ZPA firmware or app by Zoom Device Manager (ZDM) group ID.

        **Scopes:** `device:write:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`
      operationId: Devices_upgradeZpaOsApp
      security:
      - openapi_oauth:
        - device:write:admin
        openapi_authorization: []
      summary: upgrade zpa os/app
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--devices-zpa-upgrade
      x-content-type: application/json
      x-accepts: application/json
  /devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}:
    delete:
      description: |-
        Remove a ZPA device from the device manager, by vendor and mac address.

        **Scopes:** `device:write:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`
      operationId: Devices_removeZpaDeviceByVendorAndMacAddress
      security:
      - openapi_oauth:
        - device:write:admin
        openapi_authorization: []
      summary: Delete ZPA device by vendor and mac address
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--devices-zpa-vendors-vendor-mac_addresses-macAddress
      x-accepts: application/json
  /devices/zpa/zdm_groups/{zdmGroupId}/versions:
    get:
      description: |-
        Get ZPA firmware and app version information that can be upgraded for devices.

        **Scopes:** `device:read:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`
      operationId: Devices_getZpaVersionInfo
      security:
      - openapi_oauth:
        - device:read:admin
        openapi_authorization: []
      summary: Get ZPA version info
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--devices-zpa-zdm_groups-zdmGroupId-versions
      x-accepts: application/json
  /devices/{deviceId}:
    delete:
      description: "Delete a device from a Zoom account. \n\n**Prerequisites:**\n\
        * Device must be enrolled in ZMD (Zoom Device Management)\n\n**Scopes:** `device:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Devices_removeDeviceZMD
      security:
      - openapi_oauth:
        - device:write:admin
        openapi_authorization: []
      summary: Delete device
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--devices-deviceId
      x-accepts: application/json
    get:
      description: |-
        Retrieve a device's details.

        **Scopes:** `device:read:admin`,`device:write:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`
      operationId: Devices_getDetail
      security:
      - openapi_oauth:
        - device:read:admin
        - device:write:admin
        openapi_authorization: []
      summary: Get device detail
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--devices-deviceId
      x-accepts: application/json
    patch:
      description: "Change device name. \n\n**Prerequisites:**\n* Device must be enrolled\
        \ in ZMD (Zoom Device Management)\n\n**Scopes:** `device:write:admin`\n\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Devices_updateDeviceName
      security:
      - openapi_oauth:
        - device:write:admin
        openapi_authorization: []
      summary: 'Change device '
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--devices-deviceId
      x-content-type: application/json
      x-accepts: application/json
  /devices/{deviceId}/assignment:
    patch:
      description: "This Device API lets you change device association from one Zoom\
        \ Room to another. \n\n**Prerequisites:**\n* Device must be enrolled in ZMD\
        \ (Zoom Device Management) \n\n\n\n**Scopes:** `device:write:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Devices_changeDeviceAssociation
      security:
      - openapi_oauth:
        - device:write:admin
        openapi_authorization: []
      summary: Change device association
      tags:
      - Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--devices-deviceId-assignment
      x-content-type: application/json
      x-accepts: application/json
  /h323/devices:
    get:
      description: "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector)\
        \ to join a Zoom cloud meeting. A Room Connector can also call out to a H.323\
        \ or SIP device to join a Zoom cloud meeting. Use this API to list all H.323/SIP\
        \ Devices on a Zoom account.  \n   \n\n \n\n\n**Scopes:** `h323:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: H323Devices_listDevices
      security:
      - openapi_oauth:
        - h323:read:admin
        openapi_authorization: []
      summary: List H.323/SIP devices
      tags:
      - H323 Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--h323-devices
      x-accepts: application/json
    post:
      description: "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector)\
        \ to join a Zoom cloud meeting. A Room Connector can also call out to a H.323\
        \ or SIP device to join a Zoom cloud meeting. Use this API to add a H.323/SIP\
        \ device to your Zoom account  \n   \n\n \n\n\n**Scopes:** `h323:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: H323Devices_createDevice
      security:
      - openapi_oauth:
        - h323:write:admin
        openapi_authorization: []
      summary: Create a H.323/SIP device
      tags:
      - H323 Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--h323-devices
      x-content-type: application/json
      x-accepts: application/json
  /h323/devices/{deviceId}:
    delete:
      description: "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector)\
        \ to join a Zoom cloud meeting. A Room Connector can also call out to a H.323\
        \ or SIP device to join a Zoom cloud meeting. Use this API to delete a H.323/SIP\
        \ device from your Zoom account.  \n   \n\n \n\n\n**Scopes:** `h323:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: H323Devices_deleteDevice
      security:
      - openapi_oauth:
        - h323:write:admin
        openapi_authorization: []
      summary: Delete a H.323/SIP device
      tags:
      - H323 Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--h323-devices-deviceId
      x-accepts: application/json
    patch:
      description: "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector)\
        \ to join a Zoom cloud meeting. A Room Connector can also call out to a H.323\
        \ or SIP device to join a Zoom cloud meeting. Use this API to edit information\
        \ of a H.323/SIP device from your Zoom account.  \n   \n\n \n\n\n**Scopes:**\
        \ `h323:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: H323Devices_updateDeviceInfo
      security:
      - openapi_oauth:
        - h323:write:admin
        openapi_authorization: []
      summary: Update a H.323/SIP device
      tags:
      - H323 Devices
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--h323-devices-deviceId
      x-content-type: application/json
      x-accepts: application/json
  /live_meetings/{meetingId}/chat/messages/{messageId}:
    delete:
      description: "Delete a message in a live meeting, based on ID. \n\n**Prerequisites:**\
        \ \n* Have Zoom enable the DLP for the in-meeting chat feature to use this\
        \ API.\n\n**Scopes:** `meeting:write`,`meeting:write:admin`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Meetings_deleteMeetingChatMessage
      security:
      - openapi_oauth:
        - meeting:write
        - meeting:write:admin
        openapi_authorization: []
      summary: Delete a live meeting message
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--live_meetings-meetingId-chat-messages-messageId
      x-accepts: application/json
    patch:
      description: |-
        Update a message in a live meeting, based on ID. **Prerequisites:** * Have Zoom enable the DLP for the in-meeting chat feature to use this API.

        **Scopes:** `meeting:write`,`meeting:write:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`
      operationId: Meetings_updateMessage
      security:
      - openapi_oauth:
        - meeting:write
        - meeting:write:admin
        openapi_authorization: []
      summary: Update a live meeting message
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--live_meetings-meetingId-chat-messages-messageId
      x-content-type: application/json
      x-accepts: application/json
  /live_meetings/{meetingId}/events:
    patch:
      description: "Control [in-meeting](https://support.zoom.us/hc/en-us/articles/360021921032-In-Meeting-Controls)\
        \ features. In-meeting controls include starting and stopping a recording,\
        \ pausing and resuming a recording, and inviting participants. \n\n**Note:**\
        \ This API's recording control only works for cloud recordings. It does **not**\
        \ work for local recordings. \n\n**Prerequisites:**\n* The meeting **must**\
        \ be a live meeting **except** inviting participants to the meeting through\
        \ [call out (phone)/(room system)]. \n* Recording control: [Cloud recording](https://support.zoom.us/hc/en-us/articles/360060231472-Enabling-cloud-recording)\
        \ must be enabled on the account. \n* The user calling this API must be the\
        \ host or an alternative meeting host.\n\n \n\n**Scopes:** `meeting:write`,`meeting:write:admin`,`meeting:master`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Meetings_controlInMeetingFeatures
      security:
      - openapi_oauth:
        - meeting:write
        - meeting:write:admin
        - meeting:master
        openapi_authorization: []
      summary: Use in-meeting controls
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--live_meetings-meetingId-events
      x-content-type: application/json
      x-accepts: application/json
  /meetings/meeting_summaries:
    get:
      description: |-
        Generates a list of all meeting summaries for an account.

        **Prerequisites**
        * Host user type must be Pro or higher plan.
        * The Meeting Summary with AI Companion feature enabled in the host's account.
        * E2ee meetings do not have summary feature enabled.

        **Scopes:** `meeting_summary:read:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`
      operationId: Meetings_listMeetingSummaries
      security:
      - openapi_oauth:
        - meeting_summary:read:admin
        openapi_authorization: []
      summary: List meeting summaries of an account
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meeting_summaries
      x-accepts: application/json
  /meetings/{meetingId}:
    delete:
      description: "Delete a meeting.  \n   \n\n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_removeMeeting
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Delete a meeting
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--meetings-meetingId
      x-accepts: application/json
    get:
      description: "Retrieve the given meeting's details. \n \n\n \n\n\n**Scopes:**\
        \ `meeting:read`,`meeting:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Meetings_getDetails
      security:
      - openapi_oauth:
        - meeting:read
        - meeting:read:admin
        openapi_authorization: []
      summary: Get a meeting
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId
      x-accepts: application/json
    patch:
      description: "Update meeting details.\n\n**Note** \n* The `start_time` value\
        \ **must** be a future date. If the value is omitted or a date is in the past,\
        \ the API ignores this value and does **not** update any recurring meetings.\
        \ \n* The `recurrence` object is **required**.\n* This API has a rate limit\
        \ of **100 requests per day**. You can update a meeting for a maximum of **100\
        \ times within a 24-hour period**. \n\n\n\n\n**Scopes:** `meeting:write`,`meeting:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Meetings_updateDetails
      security:
      - openapi_oauth:
        - meeting:write
        - meeting:write:admin
        openapi_authorization: []
      summary: Update a meeting
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--meetings-meetingId
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/batch_polls:
    post:
      description: "Polls allow the meeting host to survey attendees. Create batch\
        \ [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)\
        \ for a meeting.  \n   \n\n \n\n**Prerequisites**:  \n \n* Host user type\
        \ must be **Pro** or higher plan.\n* Polling feature must be enabled in the\
        \ host's account.\n* Meeting must be a scheduled meeting. Instant meetings\
        \ do not have polling features enabled.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_createBatchPolls
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Perform batch poll creation
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--meetings-meetingId-batch_polls
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/batch_registrants:
    post:
      description: "Register up to 30 registrants at once for a meeting that requires\
        \ [registration](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\
        \   \n \n\n**Prerequisites:**  \n \n* The meeting host must be a Licensed\
        \ user.\n* The meeting must require registration and should be of type `2`,\
        \ i.e., they should be scheduled meetings. Instant meetings and Recurring\
        \ meetings are not supported by this API.  \n   \n\n \n\n\n**Scopes:** `meeting:write`,`meeting:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Meetings_batchRegistrantsCreate
      security:
      - openapi_oauth:
        - meeting:write
        - meeting:write:admin
        openapi_authorization: []
      summary: Perform batch registration
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--meetings-meetingId-batch_registrants
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/invitation:
    get:
      description: |-
        Retrieve the meeting invitation note for a specific meeting.

        **Scopes:** `meeting:read`,`meeting:read:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`
      operationId: Meetings_getInvitationNote
      security:
      - openapi_oauth:
        - meeting:read
        - meeting:read:admin
        openapi_authorization: []
      summary: Get meeting invitation
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-invitation
      x-accepts: application/json
  /meetings/{meetingId}/invite_links:
    post:
      description: |-
        Create a batch of invitation links for a meeting.



        **Scopes:** `meeting:write:admin`,`meeting:write`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: Meetings_createInviteLinks
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Create meeting's invite links
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--meetings-meetingId-invite_links
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/jointoken/live_streaming:
    get:
      description: "Get a meeting's join token to allow live streaming. The join token\
        \ allows a recording bot implemented using Zoom meeting SDK to connect to\
        \ a Zoom meeting &quot;hosted by the issuer of the token&quot;, and can call\
        \ the streaming method automatically. It supports both regular live streaming,\
        \ and raw streaming. \n\n**Prerequisites:** \n* A Pro or higher plan for the\
        \ meeting host. \n* The **Allow livestreaming of meetings** user setting enabled\
        \ in the Zoom web portal.\n\n**Scopes:** `meeting_token:read:admin:live_streaming`,`meeting_token:read:live_streaming`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_getJoinToken
      security:
      - openapi_oauth:
        - meeting_token:read:admin:live_streaming
        - meeting_token:read:live_streaming
        openapi_authorization: []
      summary: Get a meeting's join token for live streaming
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-jointoken-live_streaming
      x-accepts: application/json
  /meetings/{meetingId}/jointoken/local_archiving:
    get:
      description: "Get a meeting's archive token to allow local archiving. The archive\
        \ token allows a meeting SDK app or bot to get archive permission to access\
        \ the meeting's raw audio and video media stream in real-time. \n\n**Prerequisites:**\
        \ \n* A Pro or higher plan for the meeting host. \n* The **Archive meetings\
        \ and webinars** account setting enabled in the Zoom web portal.\n\n**Scopes:**\
        \ `meeting_token:read:admin:local_archiving`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_getMeetingArchiveTokenForLocalArchiving
      security:
      - openapi_oauth:
        - meeting_token:read:admin:local_archiving
        openapi_authorization: []
      summary: Get a meeting's archive token for local archiving
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-jointoken-local_archiving
      x-accepts: application/json
  /meetings/{meetingId}/jointoken/local_recording:
    get:
      description: "Get a meeting's join token to allow for local recording. The join\
        \ token lets a recording bot implemented using Zoom Meeting SDK to connect\
        \ to a Zoom meeting. The recording bot can then automatically start locally\
        \ recording. This supports both regular and raw local recording types. \n\n\
        **Prerequisites:** \n* The **Local recording** user setting enabled in the\
        \ Zoom web portal.\n\n**Scopes:** `meeting_token:read:local_recording`,`meeting_token:read:admin:local_recording`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Meetings_getJoinTokenLocalRecording
      security:
      - openapi_oauth:
        - meeting_token:read:local_recording
        - meeting_token:read:admin:local_recording
        openapi_authorization: []
      summary: Get a meeting's join token for local recording
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-jointoken-local_recording
      x-accepts: application/json
  /meetings/{meetingId}/livestream:
    get:
      description: "Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)\
        \ to a custom platform. Get a meeting's livestream configuration details such\
        \ as Stream URL, Stream Key and Page URL.  \n   \n\n \n**Prerequisites:**\
        \  \n \n* Meeting host must be a licensed user with a Pro or higher plan.\
        \  \n \n* Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5)\
        \ for the meeting.  \n   \n\n \n\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_getLivestreamDetails
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: Get livestream details
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-livestream
      x-accepts: application/json
    patch:
      description: "Update a meeting's livestream information. Zoom allows users to\
        \ [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)\
        \ to a custom platform.\n\n**Prerequisites:** \n* Meeting host must have a\
        \ Pro license.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_updateLivestream
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Update a livestream
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--meetings-meetingId-livestream
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/livestream/status:
    patch:
      description: "Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)\
        \ to a custom platform. Update the status of a meeting's livestream.  \n \
        \  \n\n \n**Prerequisites:**  \n \n* Meeting host must have a Pro license.\
        \  \n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_livestreamStatusUpdate
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Update Live Stream Status
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--meetings-meetingId-livestream-status
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/meeting_summary:
    get:
      description: |-
        Displays information about a meeting summary.

        **Prerequisites**:
        * Host user type must be Pro or higher plan.
        * The Meeting Summary with AI Companion feature enabled in the host's account.
        * E2ee meetings do not have summary feature enabled.

        **Scopes:** `meeting_summary:read:admin`,`meeting_summary:read`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`
      operationId: Meetings_getMeetingSummary
      security:
      - openapi_oauth:
        - meeting_summary:read:admin
        - meeting_summary:read
        openapi_authorization: []
      summary: Get a meeting summary
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-meeting_summary
      x-accepts: application/json
  /meetings/{meetingId}/polls:
    get:
      description: "Polls allow the meeting host to survey attendees. List all [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)\
        \ of a meeting.  \n   \n\n \n\n**Prerequisites**:  \n \n* Host user type must\
        \ be **Pro** or higher plan.\n* Meeting must be a scheduled meeting. Instant\
        \ meetings do not have polling features enabled.\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_listMeetingPolls
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: List meeting polls
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-polls
      x-accepts: application/json
    post:
      description: "Polls allow the meeting host to survey attendees. Create a [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)\
        \ for a meeting.  \n   \n\n \n\n**Prerequisites**:  \n \n* Host user type\
        \ must be **Pro** or higher plan.\n* Polling feature must be enabled in the\
        \ host's account.\n* Meeting must be a scheduled meeting. Instant meetings\
        \ do not have polling features enabled.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_createPoll
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Create a meeting poll
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--meetings-meetingId-polls
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/polls/{pollId}:
    delete:
      description: "Polls allow the meeting host to survey attendees. Delete a meeting\
        \ [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).\
        \  \n \n**Prerequisites**:  \n \n* Host user type must be **Pro**.\n* Polling\
        \ feature should be enabled in the host's account.\n* Meeting must be a scheduled\
        \ meeting. Instant meetings do not have polling features enabled.\n\n**Scopes:**\
        \ `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_pollDelete
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Delete a meeting poll
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--meetings-meetingId-polls-pollId
      x-accepts: application/json
    get:
      description: "Polls allow the meeting host to survey attendees. Retrieve information\
        \ about a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).\
        \  \n   \n\n \n\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_getPoll
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: Get a meeting poll
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-polls-pollId
      x-accepts: application/json
    put:
      description: "Polls allow the meeting host to survey attendees. Update information\
        \ of a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)\
        \  \n   \n\n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_updateMeetingPoll
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Update a meeting poll
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--meetings-meetingId-polls-pollId
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/registrants:
    get:
      description: "A host or a user with admin permission can require [registration\
        \ for a Zoom meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\
        \ List users that have registered for a meeting.  \n   \n\n \n\n\n**Scopes:**\
        \ `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Meetings_listRegistrants
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: List meeting registrants
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-registrants
      x-accepts: application/json
    post:
      description: "Create and submit a user's registration to a meeting. See [Customizing\
        \ webinar registration](https://support.zoom.us/hc/en-us/articles/202835649-Customizing-webinar-registration)\
        \ for details on how to set the requirements for these fields. Note that there\
        \ is a maximum limit of 4,999 registrants per meeting and users will see an\
        \ error if the meeting's capacity is reached. \n\n **Prerequisites:** \n*\
        \ The host must be a **Licensed** user type.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_addRegistrant
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Add a meeting registrant
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--meetings-meetingId-registrants
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/registrants/questions:
    get:
      description: "List registration questions that will be displayed to users while\
        \ [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\
        \  \n \n\n\n\n**Scopes:** `meeting:read`,`meeting:read:admin`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_listRegistrationQuestions
      security:
      - openapi_oauth:
        - meeting:read
        - meeting:read:admin
        openapi_authorization: []
      summary: 'List registration questions '
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-registrants-questions
      x-accepts: application/json
    patch:
      description: "Update registration questions that will be displayed to users\
        \ while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\
        \  \n   \n\n \n\n\n**Scopes:** `meeting:write`,`meeting:write:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_updateRegistrationQuestions
      security:
      - openapi_oauth:
        - meeting:write
        - meeting:write:admin
        openapi_authorization: []
      summary: Update registration questions
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--meetings-meetingId-registrants-questions
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/registrants/status:
    put:
      description: "Update a meeting registrant's status by either approving, cancelling\
        \ or denying a registrant from joining the meeting.  \n   \n\n \n\n\n**Scopes:**\
        \ `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Meetings_updateRegistrantStatus
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Update registrant's status
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--meetings-meetingId-registrants-status
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/registrants/{registrantId}:
    delete:
      description: "Delete a meeting registrant.  \n   \n\n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_deleteRegistrant
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Delete a meeting registrant
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--meetings-meetingId-registrants-registrantId
      x-accepts: application/json
    get:
      description: "Retrieve details on a specific user who has registered for the\
        \ meeting. A host or a user with administrative permissions can require [registration\
        \ for Zoom meetings](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\n\
        \n**Prerequisites:** \n* The account must have a Meeting plan\n\n**Scopes:**\
        \ `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_getRegistrantDetails
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: Get a meeting registrant
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-registrants-registrantId
      x-accepts: application/json
  /meetings/{meetingId}/sip_dialing:
    post:
      description: "Get a meeting's SIP URI.  The URI consists of the meeting ID,\
        \ (optional, user-supplied) passcode and participant identifier code.  The\
        \ API return data also includes additional fields to indicate whether the\
        \ API caller has a valid Cloud Room Connector subscription, the participant\
        \ identifier code from the URI, and the SIP URI validity period (in seconds).\
        \ \n\n\n\n**Scopes:** `meeting:write:sip_dialing`,`meeting:write:admin:sip_dialing`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Meetings_getSipUriWithPasscode
      security:
      - openapi_oauth:
        - meeting:write:sip_dialing
        - meeting:write:admin:sip_dialing
        openapi_authorization: []
      summary: Get a meeting SIP URI with Passcode
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--meetings-meetingId-sip_dialing
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/status:
    put:
      description: "Update the status of a meeting.  \n   \n\n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_updateMeetingStatus
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Update meeting status
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--meetings-meetingId-status
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/survey:
    delete:
      description: "Delete a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting).\
        \ \n\n **Prerequisites:** \n* The host must be a **Pro** user type. \n* The\
        \ [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys)\
        \ feature enabled in the host's account. \n* The meeting must be a scheduled\
        \ meeting. Instant meetings do not have survey features enabled.\n\n**Scopes:**\
        \ `meeting:write`,`meeting:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_deleteMeetingSurvey
      security:
      - openapi_oauth:
        - meeting:write
        - meeting:write:admin
        openapi_authorization: []
      summary: Delete a meeting survey
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--meetings-meetingId-survey
      x-accepts: application/json
    get:
      description: |-
        Display information about a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting).  **Prerequisites:** * The host has a **Pro** license. * The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature is enabled on the host's account. * The meeting must be a scheduled meeting. Instant meetings do not have survey features enabled.

        **Scopes:** `meeting:read`,`meeting:read:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`
      operationId: Meetings_getMeetingSurvey
      security:
      - openapi_oauth:
        - meeting:read
        - meeting:read:admin
        openapi_authorization: []
      summary: Get a meeting survey
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-survey
      x-accepts: application/json
    patch:
      description: |-
        Update a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting).  **Prerequisites:** * The host must be a **Pro** user type. * The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature is enabled in the host's account. * The meeting must be a scheduled meeting. Instant meetings do not have survey features enabled.

        **Scopes:** `meeting:write:admin`,`meeting:write`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`
      operationId: Meetings_updateSurvey
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Update a meeting survey
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--meetings-meetingId-survey
      x-content-type: application/json
      x-accepts: application/json
  /meetings/{meetingId}/token:
    get:
      description: "Get a meeting's [closed caption token (caption URL)](https://support.zoom.us/hc/en-us/articles/115002212983-Using-a-third-party-closed-captioning-service).\
        \ This token lets you use a third-party service to stream text to their closed\
        \ captioning software to the Zoom meeting. \n\n**Prerequisites:** \n* The\
        \ **Closed captioning** setting enabled in the Zoom web portal. \n* The **Allow\
        \ use of caption API Token to integrate with 3rd-party Closed Captioning services**\
        \ setting enabled.\n\n**Scopes:** `meeting:read`,`meeting:read:admin`\n\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_getMeetingToken
      security:
      - openapi_oauth:
        - meeting:read
        - meeting:read:admin
        openapi_authorization: []
      summary: Get meeting's token
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--meetings-meetingId-token
      x-accepts: application/json
  /past_meetings/{meetingId}:
    get:
      description: "Get information about a past meeting. \n\n \n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Meetings_getDetails
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: Get past meeting details
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_meetings-meetingId
      x-accepts: application/json
  /past_meetings/{meetingId}/instances:
    get:
      description: "Return a list of past meeting instances. \n\n \n\n**Scopes:**\
        \ `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Meetings_listPastMeetingInstances
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: List past meeting instances
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_meetings-meetingId-instances
      x-accepts: application/json
  /past_meetings/{meetingId}/participants:
    get:
      description: "Retrieve information on participants from a past meeting. Note\
        \ the API doesn't return results if there's only one participant in a meeting.\
        \  \n   \n\n \n**Prerequisites:**  \n \n* Paid account on a Pro or higher\
        \ plan.\n\n  \n    \n   **Note**: Please double encode your UUID when using\
        \ this API if the UUID begins with a '/'or contains '//' in it.\n\n\n**Scopes:**\
        \ `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Meetings_getPastMeetingParticipants
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: Get past meeting participants
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_meetings-meetingId-participants
      x-accepts: application/json
  /past_meetings/{meetingId}/polls:
    get:
      description: "[Polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)\
        \ allow the meeting host to survey attendees. List poll results of a meeting.\
        \  \n   \n\n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro**.\n\
        * Meeting must be a scheduled meeting. Instant meetings do not have polling\
        \ features enabled.\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Meetings_listPastMeetingPolls
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: List past meeting's poll results
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_meetings-meetingId-polls
      x-accepts: application/json
  /past_meetings/{meetingId}/qa:
    get:
      description: "The question &amp; answer (Q&amp;A) feature for Zoom Meetings\
        \ lets attendees ask questions during a meeting and lets the other attendees\
        \ answer those questions.  \n \nList Q&amp;A of a specific meeting.\n\n**Prerequisites:**\
        \  \n \n* \n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Meetings_listPastMeetingQA
      security:
      - openapi_oauth:
        - meeting:read:admin
        - meeting:read
        openapi_authorization: []
      summary: List past meetings' Q&A
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_meetings-meetingId-qa
      x-accepts: application/json
  /users/{userId}/meeting_templates:
    get:
      description: |-
        List available [meeting templates](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates) for a user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.



        **Scopes:** `meeting:read`,`meeting:read:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: Meetings_listMeetingTemplates
      security:
      - openapi_oauth:
        - meeting:read
        - meeting:read:admin
        openapi_authorization: []
      summary: List meeting templates
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-meeting_templates
      x-accepts: application/json
    post:
      description: "Create a meeting template from an existing meeting. \n\n\n\n**Scopes:**\
        \ `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Meetings_createTemplateFromMeeting
      security:
      - openapi_oauth:
        - meeting:write:admin
        - meeting:write
        openapi_authorization: []
      summary: Create a meeting template from an existing meeting
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users-userId-meeting_templates
      x-content-type: application/json
      x-accepts: application/json
  /users/{userId}/meetings:
    get:
      description: "List a meeting host user's scheduled meetings. For user-level\
        \ apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)\
        \ instead of the `userId` parameter. \n\n**Note** \n* This API **only** supports\
        \ scheduled meetings. This API does not return information about instant meetings.\
        \ \n* This API only returns a user's [unexpired meetings](https://support.zoom.us/hc/en-us/articles/201362373-Meeting-ID#h_c73f9b08-c1c0-4a1a-b538-e01ebb98e844).\
        \ \n\n \n\n**Scopes:** `meeting:read`,`meeting:read:admin`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Meetings_listHostScheduled
      security:
      - openapi_oauth:
        - meeting:read
        - meeting:read:admin
        openapi_authorization: []
      summary: List meetings
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-meetings
      x-accepts: application/json
    post:
      description: "[Create a meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings)\
        \ for a user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)\
        \ instead of the `userId` parameter.\n\n* A meeting's `start_url` value is\
        \ the URL a host or an alternative host can use to start a meeting. The expiration\
        \ time for the `start_url` value is **two hours** for all regular users.\n\
        * For `custCreate` meeting hosts (users created with the `custCreate` parameter\
        \ via the [**Create users**](https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/userCreate)\
        \ API), the expiration time of the `start_url` parameter is **90 days** from\
        \ the generation of the `start_url`.\n\n**Note:** \n\nFor security reasons,\
        \ the recommended way to programmatically get the updated `start_url` value\
        \ after expiry is to call the [**Get a meeting**](/api-reference/zoom-api/methods#operation/meeting)\
        \ API. Refer to the `start_url` value in the response. \n\n **100 requests\
        \ per day**. The rate limit is applied against the `userId` of the **meeting\
        \ host** used to make the request.\n\n**Scopes:** `meeting:write`,`meeting:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Meetings_createMeeting
      security:
      - openapi_oauth:
        - meeting:write
        - meeting:write:admin
        openapi_authorization: []
      summary: Create a meeting
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users-userId-meetings
      x-content-type: application/json
      x-accepts: application/json
  /users/{userId}/upcoming_meetings:
    get:
      description: |-
        List a Zoom user's upcoming meetings. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.

        **Note**
        * This API includes the meetings that Zoom users schedule and the meetings they are invited to join.
        * This API **only** includes upcoming meetings within the next 24 hours.

        **Scopes:** `meeting:read`,`meeting:read:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`
      operationId: Meetings_listUpcomingMeetings
      security:
      - openapi_oauth:
        - meeting:read
        - meeting:read:admin
        openapi_authorization: []
      summary: List upcoming meetings
      tags:
      - Meetings
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-upcoming_meetings
      x-accepts: application/json
  /users/{userId}/pac:
    get:
      description: "Retrieve a list of a user's [personal audio conference (PAC)](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference)\
        \ accounts. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)\
        \ instead of the `userId` parameter. \n\n PAC allows Pro or higher account\
        \ holders to host meetings through PSTN (phone dial-in) only. \n\n **Prerequisites**\
        \ \n* A Pro or higher plan with an [Audio Conferencing](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference)\
        \ subscription. \n* The [**Personal Audio Conference**](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference#h_01F5BPM447M6QDJXX50RSFXKJ3)\
        \ setting enabled in the user's profile.\n\n**Scopes:** `pac:read:admin`,`pac:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Pac_listAccounts
      security:
      - openapi_oauth:
        - pac:read:admin
        - pac:read
        openapi_authorization: []
      summary: List a user's PAC accounts
      tags:
      - PAC
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-pac
      x-accepts: application/json
  /report/activities:
    get:
      description: "Retrieve a list of sign in / sign out activity logs [report](https://support.zoom.us/hc/en-us/articles/201363213-Getting-Started-with-Reports)\
        \ of users under a Zoom account.  \n \n**Prerequisites**  \n \n* Pro or higher\
        \ plan.  \n \n\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_listSignInSignOutActivities
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get sign In / sign out activity report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-activities
      x-accepts: application/json
  /report/billing:
    get:
      description: "Get department billing reports of a Zoom account.\n\n**Prerequisites:**\
        \  \n \n* Pro or a higher account with Department Billing option enabled.\
        \ Contact Zoom Support team for details.\n\n\n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getBillingDepartmentReports
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get billing reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-billing
      x-accepts: application/json
  /report/billing/invoices:
    get:
      description: "Get department billing invoices reports for a specific billing\
        \ period. Provide the `billing_id` of the billing period for which you would\
        \ like to retrieve the invoices for. This ID can be retrieved from **Get Billing\
        \ Reports** API. \n\n**Prerequisites:**  \n \n* Pro or a higher account with\
        \ Department Billing option enabled. Contact the Zoom Support team to enable\
        \ this feature.\n\n\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getBillingInvoices
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get billing invoice reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-billing-invoices
      x-accepts: application/json
  /report/cloud_recording:
    get:
      description: "Retrieve cloud recording usage report for a specified period.\
        \ You can only get cloud recording reports that is one day earlier than the\
        \ current date and for the most recent period of 6 months. The date gap between\
        \ from and to dates should be smaller or equal to 30 days.   \n \n**Prerequisites**\
        \  \n \n* Pro or higher plan.  \n \n\n\n**Scopes:** `report:read:admin`\n\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getCloudRecordingUsageReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get cloud recording usage report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-cloud_recording
      x-accepts: application/json
  /report/daily:
    get:
      description: "Retrieve daily report to access the account-wide usage of Zoom\
        \ services for each day in a given month. It lists the number of new users,\
        \ meetings, participants, and meeting minutes.  \n \n**Prerequisites**  \n\
        \ \n* Pro or higher plan.  \n \n\n\n**Scopes:** `report:read:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getDailyUsageReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get daily usage report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-daily
      x-accepts: application/json
  /report/meetings/{meetingId}:
    get:
      description: "Get a detailed report for a past meeting.   \n \n**Prerequisites:**\
        \  \n \n* Pro or a higher plan.  \n \n\n \n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getMeetingDetailReports
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get meeting detail reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-meetings-meetingId
      x-accepts: application/json
  /report/meetings/{meetingId}/participants:
    get:
      description: "Return a report of a past meeting with two or more participants,\
        \ including the host. To return a report for past meeting with only **one**\
        \ participant, use the [**List meeting participants**](https://developers.zoom.us)\
        \ API. \n\n**Note:** \n\nThis API may return empty values for participants'\
        \ `user_name`, `ip_address`, `location`, and `email` responses when the account\
        \ calling this API: \n* Does **not** have a signed HIPAA business associate\
        \ agreement (BAA). \n* Is a [**legacy** HIPAA BAA account](https://developers.zoom.us).\
        \ \n\n**Prerequisites:** \n* A Pro or a higher plan.\n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getMeetingParticipantReports
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get meeting participant reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-meetings-meetingId-participants
      x-accepts: application/json
  /report/meetings/{meetingId}/polls:
    get:
      description: "Use this API to get a report of [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)\
        \ results for a past meeting. \n\n **Prerequisites:** \n* A Pro or a higher\
        \ plan.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getMeetingPollReports
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get meeting poll reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-meetings-meetingId-polls
      x-accepts: application/json
  /report/meetings/{meetingId}/qa:
    get:
      description: "Retrieve a report on questions asked and answered by participants\
        \ from past meetings.   \n   \n\n\n\n \n**Prerequisites:**  \n \n* Pro plan\
        \ or higher.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Reports_getMeetingQaReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get meeting Q&A report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-meetings-meetingId-qa
      x-accepts: application/json
  /report/meetings/{meetingId}/survey:
    get:
      description: "Retrieve a report on past [meeting survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559).\
        \  \n   \n\n \n**Prerequisites:**  \n \n* Pro or a higher plan.\n\n**Scopes:**\
        \ `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Reports_getMeetingSurveyReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get meeting survey report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-meetings-meetingId-survey
      x-accepts: application/json
  /report/operationlogs:
    get:
      description: "The [Operations Logs](https://support.zoom.us/hc/en-us/articles/360032748331-Operation-Logs)\
        \ report allows you to audit admin and user activity, such as adding a new\
        \ user, changing account settings, and deleting recordings.  \n \nUse this\
        \ API to retrieve operation logs report for a specified period of time.  \n\
        \ \n**Prerequisites:**  \n \n* Pro or higher plan.\n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getOperationLogsReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get operation logs report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-operationlogs
      x-accepts: application/json
  /report/telephone:
    get:
      description: "The [telephone report](https://support.zoom.us/hc/en-us/articles/206514816-Telephone-reports)\
        \ allows you to view who dialed into meetings via phone (Audio Conferencing\
        \ or SIP Connected Audio) and which number they dialed into and other details.\
        \ Use this API to get telephone report for a specified period of time.\n\n\
        **Prerequisites:**  \n \n* Pro or higher plan.\n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getTelephoneReports
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get telephone reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-telephone
      x-accepts: application/json
  /report/upcoming_events:
    get:
      description: "Use this API to list upcoming meeting and/or webinar events within\
        \ a specified period of time. The report's time range is limited to one month.\n\
        \n**Prerequisites:** \n* A Pro or higher plan\n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_listUpcomingEventsReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get upcoming events report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-upcoming_events
      x-accepts: application/json
  /report/users:
    get:
      description: "Retrieve a host report for a specified period of time within the\
        \ last six months.  \nThe report time range is limited to a month. \n\nYou\
        \ can specify the type of report and date range using the query parameters.\
        \  \n\n\n* The **Active Hosts** report displays a list of meetings, participants,\
        \ and meeting minutes.\nAn **active host** is defined as any user who has\
        \ hosted at least one meeting during the during the month specified in the\
        \ `from` and `to` range.\n\n\n* The **Inactive Hosts** report pulls a list\
        \ of users who were not active during a specific period of time.   \nAn **inactive\
        \ host** is defined as any user who has not hosted any meetings during the\
        \ specified period of time for the report. to be inactive.  \n\n\n\n\n \n\n\
        \ \n\n \n**Prerequisites:**  \n \n* Pro or higher plan.\n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Reports_getActiveInactiveHostReports
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get active/inactive host reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-users
      x-accepts: application/json
  /report/users/{userId}/meetings:
    get:
      description: "Retrieve [report](https://support.zoom.us/hc/en-us/articles/216378603-Meeting-Reporting)\
        \ on past meetings and webinars for a specified time period. The time range\
        \ for the report is limited to a month and the month must fall within the\
        \ past six months.\n\nMeetings and webinars are returned only if they have\
        \ two or more unique participants.    \n   \n\n \n**Prerequisites:**  \n \n\
        * Pro or higher plan.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getMeetingReports
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get meeting reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-users-userId-meetings
      x-accepts: application/json
  /report/webinars/{webinarId}:
    get:
      description: "Retrieve a [report](https://support.zoom.us/hc/en-us/articles/201393719-Webinar-Reporting)\
        \ containing past webinar details.    \n   \n\n \n**Prerequisites:**  \n \n\
        * Pro or higher plan with Webinar add-on.\n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getWebinarDetailsReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get webinar detail reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-webinars-webinarId
      x-accepts: application/json
  /report/webinars/{webinarId}/participants:
    get:
      description: "Get a detailed report on each webinar attendee. You can get webinar\
        \ participant reports for the last 6 months. \n\n **Prerequisites:** \n* A\
        \ Pro or a higher plan with Webinar add-on enabled.\n\n**Scopes:** `report:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_webinarParticipantsList
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get webinar participant reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-webinars-webinarId-participants
      x-accepts: application/json
  /report/webinars/{webinarId}/polls:
    get:
      description: "Retrieve a report on past [webinar polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).\
        \  \n   \n\n \n**Prerequisites:**  \n \n* Pro or a higher plan with Webinar\
        \ add-on enabled.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Heavy`"
      operationId: Reports_getWebinarPollReports
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get webinar poll reports
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-webinars-webinarId-polls
      x-accepts: application/json
  /report/webinars/{webinarId}/qa:
    get:
      description: "Retrieve a report on questions asked by participants and answered\
        \ by panelists, co-hosts and hosts from past webinars.   \n\n\n   \n\n \n\
        **Prerequisites:**  \n \n* Pro or a higher plan with the Webinar add-on enabled.\n\
        \n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Reports_getWebinarQAReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get webinar Q&A report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-webinars-webinarId-qa
      x-accepts: application/json
  /report/webinars/{webinarId}/survey:
    get:
      description: "Retrieve a report on past [webinar survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559).\
        \  \n   \n\n \n**Prerequisites:**  \n \n* Pro or a higher plan with Webinar\
        \ add-on enabled.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Reports_getWebinarSurveyReport
      security:
      - openapi_oauth:
        - report:read:admin
        openapi_authorization: []
      summary: Get webinar survey report
      tags:
      - Reports
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--report-webinars-webinarId-survey
      x-accepts: application/json
  /sip_phones:
    get:
      description: "Zoom's Phone System Integration (PSI), also referred as SIP phones,\
        \ enables an organization to leverage the Zoom client to complete a softphone\
        \ registration to supported premise based PBX system. End users will have\
        \ the ability to have softphone functionality within a single client while\
        \ maintaining a comparable interface to Zoom Phone. Use this API to list SIP\
        \ phones on an account.  \n   \n\n \n**Prerequisites**:\n* Currently only\
        \ supported on Cisco and Avaya PBX systems. \n* User must enable SIP Phone\
        \ Integration by contacting the [Sales](https://zoom.us/contactsales) team.\
        \  \n  \n\n**Scopes:** `sip_phone:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: SipPhone_list
      security:
      - openapi_oauth:
        - sip_phone:read:admin
        openapi_authorization: []
      summary: List SIP phones
      tags:
      - SIP Phone
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--sip_phones
      x-accepts: application/json
    post:
      description: "Zoom's Phone System Integration (PSI), also referred as SIP phones,\
        \ enables an organization to leverage the Zoom client to complete a softphone\
        \ registration to supported premise based PBX system. End users will have\
        \ the ability to have softphone functionality within a single client while\
        \ maintaining a comparable interface to Zoom Phone. Use this API to enable\
        \ a user to use SIP phone.  \n   \n\n \n**Prerequisites**:\n* Currently only\
        \ supported on Cisco and Avaya PBX systems. \n* The account owner or account\
        \ admin must first enable SIP Phone Integration by contacting the [Sales](https://zoom.us/contactsales)\
        \ team.  \n  \n\n**Scopes:** `sip_phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: SipPhone_enableUserSipPhone
      security:
      - openapi_oauth:
        - sip_phone:write:admin
        openapi_authorization: []
      summary: Enable SIP phone
      tags:
      - SIP Phone
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--sip_phones
      x-content-type: application/json
      x-accepts: application/json
  /sip_phones/{phoneId}:
    delete:
      description: "Use this API to delete a Zoom account's SIP phone. \n\n **Prerequisites**:\
        \ \n* Currently only supported on Cisco and Avaya PBX systems. \n* The user\
        \ must enable **SIP Phone Integration** by contacting the [Zoom Sales](https://zoom.us/contactsales)\
        \ team.\n\n**Scopes:** `sip_phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: SipPhone_deletePhone
      security:
      - openapi_oauth:
        - sip_phone:write:admin
        openapi_authorization: []
      summary: Delete SIP phone
      tags:
      - SIP Phone
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--sip_phones-phoneId
      x-accepts: application/json
    patch:
      description: "Zoom's Phone System Integration (PSI), also referred as SIP phones,\
        \ enables an organization to leverage the Zoom client to complete a softphone\
        \ registration to supported premise based PBX system. End users will have\
        \ the ability to have softphone functionality within a single client while\
        \ maintaining a comparable interface to Zoom Phone. Use this API to update\
        \ information of a specific SIP Phone on a Zoom account.  \n   \n\n \n**Prerequisites**:\n\
        * Currently only supported on Cisco and Avaya PBX systems. \n* The account\
        \ owner or account admin must first enable SIP Phone Integration by contacting\
        \ the [Sales](https://zoom.us/contactsales) team.  \n  \n\n**Scopes:** `sip_phone:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: SipPhone_updateSpecificPhone
      security:
      - openapi_oauth:
        - sip_phone:write:admin
        openapi_authorization: []
      summary: Update SIP phone
      tags:
      - SIP Phone
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--sip_phones-phoneId
      x-content-type: application/json
      x-accepts: application/json
  /tsp:
    get:
      description: "Get information on Telephony Service Provider on an account level.\
        \  \n   \n\n \n**Prerequisites:**  \n \n* A Pro or a higher plan.\n\n**Scopes:**\
        \ `tsp:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Tsp_getAccountInfo
      security:
      - openapi_oauth:
        - tsp:read:admin
        openapi_authorization: []
      summary: Get account's TSP information
      tags:
      - TSP
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--tsp
      x-accepts: application/json
    patch:
      description: "Update information of the Telephony Service Provider set up on\
        \ an account.  \n \n**Prerequisites**:  \n \nTSP account option should be\
        \ enabled.  \n \n\n\n**Scopes:** `tsp:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Tsp_updateAccountTspInformation
      security:
      - openapi_oauth:
        - tsp:write:admin
        openapi_authorization: []
      summary: Update account's TSP information
      tags:
      - TSP
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--tsp
      x-content-type: application/json
      x-accepts: application/json
  /users/{userId}/tsp:
    get:
      description: "A user can have a maximum of two TSP accounts. Use this API to\
        \ list all TSP accounts of a user.  \n   \n\n \n\n\n**Scopes:** `tsp:read:admin`,`tsp:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Tsp_listUserTspAccounts
      security:
      - openapi_oauth:
        - tsp:read:admin
        - tsp:read
        openapi_authorization: []
      summary: List user's TSP accounts
      tags:
      - TSP
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-tsp
      x-accepts: application/json
    post:
      description: "Add a user's TSP account.  \n   \n\n \n\n\n**Scopes:** `tsp:write:admin`,`tsp:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Tsp_addUserTspAccount
      security:
      - openapi_oauth:
        - tsp:write:admin
        - tsp:write
        openapi_authorization: []
      summary: Add a user's TSP account
      tags:
      - TSP
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users-userId-tsp
      x-content-type: application/json
      x-accepts: application/json
  /users/{userId}/tsp/settings:
    patch:
      description: |-
        A global dial-in page can provide a list of global access numbers using which audio conferencing can be conducted. By calling this API, you can set the url for the global dial-in page of a user whose Zoom account has TSP and special TSP with third-party audio conferencing options enabled. &lt;p&gt;&lt;/p&gt;


        **Scopes:** `tsp:write:admin`,`tsp:write`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: Tsp_setGlobalDialInUrl
      security:
      - openapi_oauth:
        - tsp:write:admin
        - tsp:write
        openapi_authorization: []
      summary: Set global dial-in URL for a TSP user
      tags:
      - TSP
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--users-userId-tsp-settings
      x-content-type: application/json
      x-accepts: application/json
  /users/{userId}/tsp/{tspId}:
    delete:
      description: "Delete a user's TSP account.  \n   \n\n \n\n\n**Scopes:** `tsp:write:admin`,`tsp:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Tsp_deleteUserTspAccount
      security:
      - openapi_oauth:
        - tsp:write:admin
        - tsp:write
        openapi_authorization: []
      summary: Delete a user's TSP account
      tags:
      - TSP
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--users-userId-tsp-tspId
      x-accepts: application/json
    get:
      description: "Each user can have a maximum of two TSP accounts. Use this API\
        \ to retrieve details of a specific TSP account enabled for a specific user.\
        \  \n   \n\n \n\n\n**Scopes:** `tsp:read:admin`,`tsp:read`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Tsp_getUserTspAccount
      security:
      - openapi_oauth:
        - tsp:read:admin
        - tsp:read
        openapi_authorization: []
      summary: Get a user's TSP account
      tags:
      - TSP
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-tsp-tspId
      x-accepts: application/json
    patch:
      description: "Update a user's TSP account.  \n   \n\n \n\n\n**Scopes:** `tsp:write:admin`,`tsp:write`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Tsp_updateUserTspAccount
      security:
      - openapi_oauth:
        - tsp:write:admin
        - tsp:write
        openapi_authorization: []
      summary: Update a TSP account
      tags:
      - TSP
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--users-userId-tsp-tspId
      x-content-type: application/json
      x-accepts: application/json
  /tracking_fields:
    get:
      description: "Use this API to list all the [tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields)\
        \ on your Zoom account. Tracking fields let you analyze usage by various fields\
        \ within an organization. \n\n**Prerequisites:** \n* A Business, Education,\
        \ API or higher plan.\n\n**Scopes:** `tracking_fields:read:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: TrackingField_list
      security:
      - openapi_oauth:
        - tracking_fields:read:admin
        openapi_authorization: []
      summary: List tracking fields
      tags:
      - Tracking Field
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--tracking_fields
      x-accepts: application/json
    post:
      description: "Use this API to create a new [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields).\
        \ Tracking fields let you analyze usage by various fields within an organization.\
        \ When scheduling a meeting, tracking fields will be included in the meeting\
        \ options. \n\n**Prerequisites:** \n* A Business, Education, API or higher\
        \ plan.\n\n**Scopes:** `tracking_fields:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: TrackingField_createField
      security:
      - openapi_oauth:
        - tracking_fields:write:admin
        openapi_authorization: []
      summary: Create a tracking field
      tags:
      - Tracking Field
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--tracking_fields
      x-content-type: application/json
      x-accepts: application/json
  /tracking_fields/{fieldId}:
    delete:
      description: "Use this API to delete a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields).\
        \ \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n\
        **Scopes:** `tracking_fields:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: TrackingField_deleteField
      security:
      - openapi_oauth:
        - tracking_fields:write:admin
        openapi_authorization: []
      summary: Delete a tracking field
      tags:
      - Tracking Field
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--tracking_fields-fieldId
      x-accepts: application/json
    get:
      description: "Use this API to return information about a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields).\
        \ \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n\
        **Scopes:** `tracking_fields:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: TrackingField_get
      security:
      - openapi_oauth:
        - tracking_fields:read:admin
        openapi_authorization: []
      summary: Get a tracking field
      tags:
      - Tracking Field
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--tracking_fields-fieldId
      x-accepts: application/json
    patch:
      description: "Use this API to update a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields).\
        \ \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n\
        **Scopes:** `tracking_fields:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: TrackingField_update
      security:
      - openapi_oauth:
        - tracking_fields:write:admin
        openapi_authorization: []
      summary: Update a tracking field
      tags:
      - Tracking Field
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--tracking_fields-fieldId
      x-content-type: application/json
      x-accepts: application/json
  /live_webinars/{webinarId}/chat/messages/{messageId}:
    delete:
      description: "Deletes a message in a live webinar based on ID. \n\n**Prerequisites:**\
        \ \n* Have Zoom enable the DLP for the in-meeting chat feature to use this\
        \ API.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_deleteMessageById
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Delete a live webinar message
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--live_webinars-webinarId-chat-messages-messageId
      x-accepts: application/json
  /past_webinars/{webinarId}/absentees:
    get:
      description: "List absentees of a webinar.  \n   \n\n \n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Webinars_listAbsentees
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: Get webinar absentees
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_webinars-webinarId-absentees
      x-accepts: application/json
  /past_webinars/{webinarId}/instances:
    get:
      description: "List past webinar instances.  \n   \n\n \n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_listPastInstances
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List past webinar instances
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_webinars-webinarId-instances
      x-accepts: application/json
  /past_webinars/{webinarId}/participants:
    get:
      description: "Retrieve a list of all the participants who attended a webinar\
        \ hosted in the past. \n\n**Prerequisites:** \n* A Pro or higher plan with\
        \ a webinar add-on.\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_listParticipants
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List webinar participants
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_webinars-webinarId-participants
      x-accepts: application/json
  /past_webinars/{webinarId}/polls:
    get:
      description: "The polling feature for webinar lets you create single-choice\
        \ or multiple-choice polling questions for your webinars. This API endpoint\
        \ retrieves the results for webinar polls of a specific webinar.\n\n**Prerequisites:**\
        \  \n \n* [Webinar license](https://zoom.us/webinar)  \n \n\n\n**Scopes:**\
        \ `webinar:read:admin`,`webinar:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_listPollResults
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List past webinar poll results
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_webinars-webinarId-polls
      x-accepts: application/json
  /past_webinars/{webinarId}/qa:
    get:
      description: "List the Q&amp;A of a specific past webinar. \n\nThe [question\
        \ &amp; answer (Q&amp;A)](https://support.zoom.us/hc/en-us/articles/203686015-Getting-Started-with-Question-Answer)\
        \ feature for webinars lets attendees ask questions during the webinar and\
        \ for the panelists, co-hosts and host to answer their questions. \n\n**Prerequisites**\
        \  \n \n* [Webinar license](https://zoom.us/webinar)  \n \n\n\n**Scopes:**\
        \ `webinar:read:admin`,`webinar:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_listPastWebinarQa
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List Q&As of a past webinar
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--past_webinars-webinarId-qa
      x-accepts: application/json
  /users/{userId}/webinar_templates:
    get:
      description: |-
        Display a list of a user's [webinar templates](https://support.zoom.us/hc/en-us/articles/115001079746-Webinar-Templates). For user-level apps, pass [the `me` value](https://developers.zoom.us) instead of the `userId` parameter. When you schedule a webinar, save the settings for that webinar as a template for scheduling future webinars.  To use a template when scheduling a webinar, use the `id` value in this API response in the `template_id` field of the [**Create a webinar**](https://dev[...]

        **Scopes:** `webinar:read:admin`,`webinar:read`
      operationId: Webinars_listWebinarTemplates
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List webinar templates
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-webinar_templates
      x-accepts: application/json
    post:
      description: "Use this API to create a webinar template from an existing webinar.\
        \ \n\n\n\n**Scopes:** `webinar:write:admin`,`webinar:write`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Webinars_createWebinarTemplate
      security:
      - openapi_oauth:
        - webinar:write:admin
        - webinar:write
        openapi_authorization: []
      summary: Create a webinar template
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users-userId-webinar_templates
      x-content-type: application/json
      x-accepts: application/json
  /users/{userId}/webinars:
    get:
      description: "List all the webinars scheduled by or on behalf a webinar host.\
        \ For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)\
        \ instead of the `userId` parameter. \n\n Zoom users with a [webinar plan](https://zoom.us/webinar)\
        \ have access to creating and managing webinars. Webinars let a host broadcast\
        \ a Zoom meeting to up to 10,000 attendees. \n\n**Note** This API only returns\
        \ a user's [unexpired webinars](https://support.zoom.us/hc/en-us/articles/201362373-Meeting-ID#h_c73f9b08-c1c0-4a1a-b538-e01ebb98e844).\
        \ \n\n **Prerequisites** \n* A Pro or higher plan with the webinar add-on.\n\
        \n**Scopes:** `webinar:read:admin`,`webinar:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_listWebinars
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List webinars
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users-userId-webinars
      x-accepts: application/json
    post:
      description: "Schedule a webinar for a user who is a webinar host. For user-level\
        \ apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)\
        \ instead of the `userId` parameter. \n\n Webinars allow a host to broadcast\
        \ a Zoom meeting to up to 10,000 attendees. \n\n**Rate limit:**\nUp to a maximum\
        \ of **100 requests per day**. The rate limit is applied to the `userId` of\
        \ the **webinar host** used to make the request. \n\n**Prerequisites:** \n\
        * A Pro or higher plan with a [Webinar plan](https://zoom.us/webinar) add-on.\n\
        \n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_createWebinar
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Create a webinar
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users-userId-webinars
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}:
    delete:
      description: "Delete a webinar. \n\n\n**Prerequisites:**  \n \n* Pro or higher\
        \ plan with the webinar add-on.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_removeWebinar
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Delete a webinar
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId
      x-accepts: application/json
    get:
      description: "Get details for a scheduled Zoom Webinar.\n  \n\n   \n\n \n**Prerequisites:**\n\
        * Pro or higher plan with a Webinar add-on.\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_getDetails
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: Get a webinar
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId
      x-accepts: application/json
    patch:
      description: "Make updates to a scheduled webinar. \n\n**100 requests per day**.\
        \ The rate limit is applied to the `userId` of the **webinar host** used to\
        \ make the request. \n\n**Prerequisites** \n* A Pro or higher plan with a\
        \ webinar add-on.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_updateScheduledWebinar
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update a webinar
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--webinars-webinarId
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/batch_registrants:
    post:
      description: "Register up to 30 registrants at once for a scheduled webinar\
        \ that requires [registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-webinar-with-registration).\
        \   \n \n\n**Prerequisites:**  \n \n* The webinar host must be a licensed\
        \ user.\n* The webinar should be type `5`, a scheduled webinar. Other types\
        \ of webinars are not supported by this API.  \n   \n\n \n\n\n**Scopes:**\
        \ `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `HEAVY`"
      operationId: Webinars_createBatchRegistrants
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Perform batch registration
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-batch_registrants
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/branding:
    get:
      description: "Use this API to get the webinar's [Session Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding)\
        \ information. Session branding lets hosts visually customize a webinar by\
        \ setting a webinar wallpaper that displays behind video tiles. Session branding\
        \ also lets hosts set the Virtual Background for and apply name tags to hosts,\
        \ alternative hosts, panelists, interpreters, and speakers. \n\n **Prerequisites:**\
        \ \n* A Pro or higher plan with the Webinar add-on. \n* The **Webinar Session\
        \ Branding** setting enabled.\n\n**Scopes:** `webinar:read`,`webinar:read:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_getSessionBranding
      security:
      - openapi_oauth:
        - webinar:read
        - webinar:read:admin
        openapi_authorization: []
      summary: Get webinar's session branding
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-branding
      x-accepts: application/json
  /webinars/{webinarId}/branding/name_tags:
    delete:
      description: "Use this API to delete a webinar's [Session Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding)\
        \ name tag. \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting\
        \ enabled.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_deleteBrandingNameTag
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Delete a webinar's branding name tag
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId-branding-name_tags
      x-accepts: application/json
    post:
      description: "Use this API to create a webinar's [Session Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding)\
        \ name tag. There's a limit of 20 name tags per webinar. **Prerequisites:**\
        \ \n*  The **Webinar Session Branding** setting enabled.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Webinars_createBrandingNameTag
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Create a webinar's branding name tag
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-branding-name_tags
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/branding/name_tags/{nameTagId}:
    patch:
      description: "Use this API to update a webinar's [Session Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding)\
        \ name tag. **Prerequisites:** \n*  The **Webinar Session Branding** setting\
        \ enabled.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Webinars_updateBrandingNameTag
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update a webinar's branding name tag
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--webinars-webinarId-branding-name_tags-nameTagId
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/branding/virtual_backgrounds:
    delete:
      description: "Use this API to delete a webinar's session branding [Virtual Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background).\
        \ \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.\n\
        \n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_deleteBrandingVirtualBackground
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Delete a webinar's branding Virtual Backgrounds
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId-branding-virtual_backgrounds
      x-accepts: application/json
    patch:
      description: "Use this API to set a webinar's default session branding [Virtual\
        \ Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background).\
        \ \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting enabled.\n\
        \n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_setDefaultBrandingVirtualBackground
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Set webinar's default branding Virtual Background
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--webinars-webinarId-branding-virtual_backgrounds
      x-accepts: application/json
    post:
      description: "Use this API to upload a webinar's session branding [Virtual Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background).\
        \ Hosts and panelists can select and use these Virtual Backgrounds during\
        \ the webinar. Branding Virtual Background files have the following restrictions:\
        \ \n* A webinar cannot exceed more than 10 Virtual Background files. \n* You\
        \ can only upload image files that are in JPG/JPEG, GIF or PNG format. \n\
        * The Virtual Background file size cannot exceed 15 megabytes (MB). \n\n **Prerequisites:**\
        \ \n*  The **Webinar Session Branding** setting enabled.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Webinars_uploadBrandingVirtualBackground
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Upload a webinar's branding Virtual Background
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-branding-virtual_backgrounds
      x-content-type: multipart/form-data
      x-accepts: application/json
  /webinars/{webinarId}/branding/wallpaper:
    delete:
      description: "Use this API to delete a webinar's session branding wallpaper\
        \ file. \n\n **Prerequisites:** \n* The **Webinar Session Branding** setting\
        \ enabled.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_deleteBrandingWallpaper
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Delete a webinar's branding wallpaper
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId-branding-wallpaper
      x-accepts: application/json
    post:
      description: "Use this API to upload a webinar's session branding wallpaper\
        \ file. Webinar branding wallpaper files have the following requirements:\
        \ \n* A webinar can only have one wallpaper file. \n* You can only upload\
        \ image files that are in JPG/JPEG, GIF, or PNG format. \n* Image files must\
        \ be 16:9 ratio. The recommended image size is 1920 x 1080 pixels (px). \n\
        * The wallpaper file size cannot exceed 15 megabytes (MB). \n\n **Prerequisites:**\
        \ \n*  The **Webinar Session Branding** setting enabled.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Medium`"
      operationId: Webinars_uploadBrandingWallpaper
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Upload a webinar's branding wallpaper
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-branding-wallpaper
      x-content-type: multipart/form-data
      x-accepts: application/json
  /webinars/{webinarId}/invite_links:
    post:
      description: |-
        Create a batch of invitation links for a webinar.

        **Prerequisites:**

        * Business, Education or API Plan with the Webinar add-on.

        **Scopes:** `webinar:write`,`webinar:write:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`
      operationId: Webinars_createInviteLinks
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Create webinar's invite links
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-invite_links
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/jointoken/live_streaming:
    get:
      description: "Use this API to get a webinar's archive token to allow live streaming.\
        \ The join token allows a recording bot implemented using Zoom meeting SDK\
        \ to connect to a Zoom meeting &quot;hosted by the issuer of the token&quot;,\
        \ and can call the streaming method automatically. It supports both regular\
        \ live streaming, and raw streaming. \n\n **Prerequisites:** \n* A Pro or\
        \ higher plan with a Webinar Add-on. \n* The **Allow livestreaming of webinars**\
        \ user setting enabled in the Zoom web portal.\n\n**Scopes:** `webinar_token:read:admin:live_streaming`,`webinar_token:read:live_streaming`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_joinTokenLiveStreaming
      security:
      - openapi_oauth:
        - webinar_token:read:admin:live_streaming
        - webinar_token:read:live_streaming
        openapi_authorization: []
      summary: Get a webinar's join token for live streaming
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-jointoken-live_streaming
      x-accepts: application/json
  /webinars/{webinarId}/jointoken/local_archiving:
    get:
      description: "Use this API to get a webinar's archive token to allow local archiving.\
        \ The archive token allows a meeting SDK app or bot to get archive permission\
        \ to access the webinar's raw audio and video media stream in real-time. \n\
        \n **Prerequisites:** \n* A Pro or higher plan with a Webinar Add-on. \n*\
        \ The **Archive meetings and webinars** account setting enabled in the Zoom\
        \ web portal.\n\n**Scopes:** `webinar_token:read:admin:local_archiving`\n\n\
        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_getMeetingArchiveTokenForLocalArchiving
      security:
      - openapi_oauth:
        - webinar_token:read:admin:local_archiving
        openapi_authorization: []
      summary: Get a webinar's archive token for local archiving
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-jointoken-local_archiving
      x-accepts: application/json
  /webinars/{webinarId}/jointoken/local_recording:
    get:
      description: "Use this API to get a webinar's join token to allow for local\
        \ recording. The join token lets a recording bot implemented using Zoom Meeting\
        \ SDK to connect to a Zoom webinar. The recording bot can then automatically\
        \ start locally recording. This supports both regular and raw local recording\
        \ types. \n\n **Prerequisites:** \n* A Pro or higher plan with a Webinar Add-on.\
        \ \n* The **Local recording** user setting enabled in the Zoom web portal.\n\
        \n**Scopes:** `webinar_token:read:admin:local_recording`,`webinar_token:read:local_recording`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_getJoinTokenLocalRecording
      security:
      - openapi_oauth:
        - webinar_token:read:admin:local_recording
        - webinar_token:read:local_recording
        openapi_authorization: []
      summary: Get a webinar's join token for local recording
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-jointoken-local_recording
      x-accepts: application/json
  /webinars/{webinarId}/livestream:
    get:
      description: "Get a webinar's live stream configuration details, such as Stream\
        \ URL, Stream Key and Page URL.\n\nZoom allows users to [live stream a webinar](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)\
        \ to a custom platform.\n\n \n**Prerequisites:**  \n \n* Pro or higher plan\
        \ with the webinar add-on.  \n \n* Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5)\
        \ for the webinar.  \n\n\n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_getLiveStreamDetails
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: Get live stream details
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-livestream
      x-accepts: application/json
    patch:
      description: "Update a webinar's live stream information. \n   \n\n \n**Prerequisites:**\
        \  \n \n* Pro or higher plan with the webinar add-on.  \n \n* Live streaming\
        \ details must be [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5)\
        \ for the webinar.  \n   \n\n \n\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_updateLiveStream
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update a live stream
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--webinars-webinarId-livestream
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/livestream/status:
    patch:
      description: "Let users [live stream a webinar](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)\
        \ to a custom platform. Update the status of a webinar's live stream.  \n\
        \   \n\n \n**Prerequisites:**  \n \n* Pro or higher plan with a Webinar Add-on.\
        \  \n \n* Live streaming details must be [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5)\
        \ for the webinar.  \n   \n\n \n\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_updateLiveStreamStatus
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update live stream status
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--webinars-webinarId-livestream-status
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/panelists:
    delete:
      description: "Remove all the panelists from a webinar.  \n \n**Prerequisites:**\
        \  \n \n* Pro or a higher plan with the [webinar add-on](https://zoom.us/webinar).\
        \  \n  \n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit\
        \ Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_removePanelists
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Remove webinar panelists
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId-panelists
      x-accepts: application/json
    get:
      description: "List all of a webinar's panelists.  \n\nWebinar panelists can\
        \ view and send video, screen share, annotate, and do much more compared to\
        \ webinar attendees. \n\n\n**Prerequisites:**  \n \n* Pro or a higher plan\
        \ with [Webinar Add-on](https://zoom.us/webinar).  \n  \n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_listPanelists
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List panelists
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-panelists
      x-accepts: application/json
    post:
      description: "Panelists in a webinar can view and send video, screen share,\
        \ annotate, and do much more compared to attendees in a webinar.  \n [Add\
        \ panelists](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_7550d59e-23f5-4703-9e22-e76bded1ed70)\
        \ to a scheduled webinar.  \n\n   \n\n \n**Prerequisites:**\n* Pro or a higher\
        \ plan with the [Webinar Add-on](https://zoom.us/webinar).  \n  \n\n**Scopes:**\
        \ `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_addPanelists
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Add panelists
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-panelists
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/panelists/{panelistId}:
    delete:
      description: "[Remove](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_de31f237-a91c-4fb2-912b-ecfba8ec5ffb)\
        \ a single panelist from a webinar.  \n  Retrieve the `panelistId` by calling\
        \ **List Panelists API**.  \n\n   \n\n \n**Prerequisites:**  \n \n* Pro or\
        \ a higher plan with the [webinar add-on](https://zoom.us/webinar).  \n  \n\
        \n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_removePanelist
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Remove a panelist
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId-panelists-panelistId
      x-accepts: application/json
  /webinars/{webinarId}/polls:
    get:
      description: "List all the [polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars)\
        \ of a Webinar.  \n   \n\n \n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_listPolls
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: 'List a webinar''s polls '
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-polls
      x-accepts: application/json
    post:
      description: "Create a [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars)\
        \ for a webinar.  \n   \n\n \n\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_createPoll
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Create a webinar's poll
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-polls
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/polls/{pollId}:
    delete:
      description: "Delete a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).\
        \  \n   \n\n \n\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_deletePoll
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Delete a webinar poll
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId-polls-pollId
      x-accepts: application/json
    get:
      description: "Get a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars)\
        \ details.  \n   \n\n \n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_getPollDetails
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: Get a webinar poll
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-polls-pollId
      x-accepts: application/json
    put:
      description: "Update a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).\
        \  \n   \n\n \n\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_updatePoll
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update a webinar poll
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--webinars-webinarId-polls-pollId
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/registrants:
    get:
      description: "List all users that have registered for a given webinar. Zoom\
        \ users with a [webinar plan](https://zoom.us/webinar) have access to creating\
        \ and managing webinars. The webinar functionality lets a host broadcast a\
        \ Zoom meeting to up to 10,000 attendees. Scheduling a [webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)\
        \ requires your registrants to complete a brief form before receiving the\
        \ link to join the webinar.  \n\n\n**Prerequisites**\n* Pro or higher plan\
        \ with a Webinar Add-on.  \n \n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_listRegistrants
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List webinar registrants
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-registrants
      x-accepts: application/json
    post:
      description: "Create and submit a user's registration for a webinar. Zoom users\
        \ with a [Webinar plan](https://zoom.us/webinar) have access to creating and\
        \ managing webinars. Webinars allow hosts to broadcast a Zoom meeting to up\
        \ to 10,000 attendees. Scheduling a [webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)\
        \ requires your registrants to complete a brief form before receiving the\
        \ link to join the webinar. \n\n**Prerequisites:** \n* A Pro or higher plan\
        \ with the Webinar add-on.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_addRegistrant
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Add a webinar registrant
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-registrants
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/registrants/questions:
    get:
      description: "List registration questions and fields that are to be answered\
        \ by users while registering for a webinar. \n\n Scheduling a [webinar with\
        \ registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)\
        \ requires your registrants to complete a brief form with fields and questions\
        \ before they can receive the link to join the webinar.  \n\n  \n**Prerequisites:**\
        \  \n  \n* Pro or higher plan with the webinar add-on.\n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_listRegistrationQuestions
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: List registration questions
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-registrants-questions
      x-accepts: application/json
    patch:
      description: "Update registration questions and fields of a scheduled webinar\
        \ for users to answer during webinar registration. Scheduling a [webinar with\
        \ registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)\
        \ requires your registrants to complete a brief form with fields and questions\
        \ before they can receive the link to join the webinar.  \n   \n\n \n**Prerequisites:**\
        \  \n   \n* Pro or higher plan with a Webinar Add-on.\n* Registration option\
        \ for Webinar should be set as required to use this API. \n\n\n**Scopes:**\
        \ `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_updateRegistrationQuestions
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update registration questions
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--webinars-webinarId-registrants-questions
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/registrants/status:
    put:
      description: "Update webinar registrants' registration status. You can approve\
        \ or deny a registrant, or revoke a registrant's approval. \n\n**Scopes:**\
        \ `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_updateRegistrantStatus
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update registrant's status
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--webinars-webinarId-registrants-status
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/registrants/{registrantId}:
    delete:
      description: "Delete a webinar registrant.  \n   \n\n \n\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_deleteRegistrant
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Delete a webinar registrant
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId-registrants-registrantId
      x-accepts: application/json
    get:
      description: "Zoom users with a [webinar plan](https://zoom.us/webinar) have\
        \ access to creating and managing webinars. The webinar feature lets a host\
        \ broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [webinar\
        \ with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)\
        \ requires your registrants to complete a brief form before receiving the\
        \ link to join the webinar.  \n Use this API to get details on a specific\
        \ user who has registered for the webinar.  \n\n   \n\n \n**Prerequisites:**\
        \  \n \n* The account must have a webinar plan.\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_registrantDetails
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: Get a webinar registrant
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-registrants-registrantId
      x-accepts: application/json
  /webinars/{webinarId}/sip_dialing:
    post:
      description: "Get a webinar's SIP URI. The URI consists of the webinar ID, an\
        \ optional user-supplied passcode, and participant identifier code. The API\
        \ return data also includes additional fields to indicate whether the API\
        \ caller has a valid Cloud Room Connector subscription, the participant identifier\
        \ code from the URI, and the SIP URI validity period in seconds. \n\n**Scopes:**\
        \ `webinar:write:admin:sip_dialing`,`webinar:write:sip_dialing`\n\n**[Rate\
        \ Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_getSipUriWithPasscode
      security:
      - openapi_oauth:
        - webinar:write:admin:sip_dialing
        - webinar:write:sip_dialing
        openapi_authorization: []
      summary: Get a webinar SIP URI with Passcode
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--webinars-webinarId-sip_dialing
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/status:
    put:
      description: "Update a webinar's status. Use this API to end an ongoing webinar.\
        \  \n   \n\n \n**Prerequisites:**  \n \n* The account must hold a valid [Webinar\
        \ plan](https://zoom.us/webinar).\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_updateStatus
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update webinar status
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-put--webinars-webinarId-status
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/survey:
    delete:
      description: "Use this API to delete a [webinar survey](https://support.zoom.us/hc/en-us/articles/360048745651).\
        \ \n\n **Prerequisites:** \n* A Pro or higher plan with the Webinar Add-on.\
        \ \n* The [**Webinar Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey)\
        \ feature enabled in the host's account.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_deleteSurvey
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Delete a webinar survey
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-delete--webinars-webinarId-survey
      x-accepts: application/json
    get:
      description: "Return information about a [webinar survey](https://support.zoom.us/hc/en-us/articles/360048745651).\
        \ \n\n **Prerequisites:** \n* A Pro or higher plan with the Webinar add-on.\
        \ \n* The [**Webinar Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey)\
        \ feature enabled in the host's account.\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `LIGHT`"
      operationId: Webinars_getSurvey
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: Get a webinar survey
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-survey
      x-accepts: application/json
    patch:
      description: |-
        Update a [webinar survey](https://support.zoom.us/hc/en-us/articles/360048745651).  **Prerequisites:** * A Pro or higher plan with the Webinar add-on. * Enable the [**Webinar Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey) feature in the host's account.

        **Scopes:** `webinar:write`,`webinar:write:admin`

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`
      operationId: Webinars_updateSurvey
      security:
      - openapi_oauth:
        - webinar:write
        - webinar:write:admin
        openapi_authorization: []
      summary: Update a webinar survey
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-patch--webinars-webinarId-survey
      x-content-type: application/json
      x-accepts: application/json
  /webinars/{webinarId}/token:
    get:
      description: "Use this API to get a webinar's [closed caption token (caption\
        \ URL)](https://support.zoom.us/hc/en-us/articles/115002212983-Using-a-third-party-closed-captioning-service).\
        \ This token lets you use a third-party service to stream text to their closed\
        \ captioning software to the Zoom webinar. \n\n**Prerequisites:** \n* A Pro\
        \ or higher plan with the Webinar add-on. \n* The **Closed captioning** setting\
        \ enabled in the Zoom web portal. \n* \n* The **Allow use of caption API Token\
        \ to integrate with 3rd-party Closed Captioning services** setting enabled.\n\
        \n**Scopes:** `webinar:read`,`webinar:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `Light`"
      operationId: Webinars_getWebinarToken
      security:
      - openapi_oauth:
        - webinar:read
        - webinar:read:admin
        openapi_authorization: []
      summary: Get webinar's token
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-token
      x-accepts: application/json
  /webinars/{webinarId}/tracking_sources:
    get:
      description: "[Webinar Registration Tracking Sources](https://support.zoom.us/hc/en-us/articles/360000315683-Webinar-Registration-Source-Tracking)\
        \ allow you to see where your registrants are coming from if you share the\
        \ webinar registration page in multiple platforms. You can then use the source\
        \ tracking to see the number of registrants generated from each platform.\
        \  \n  Use this API to list information on all the tracking sources of a Webinar.\
        \  \n\n \n**Prerequisites**:  \n \n* [Webinar license](https://zoom.us/webinar).\n\
        * Registration must be required for the Webinar.\n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\
        \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**\
        \ `MEDIUM`"
      operationId: Webinars_listTrackingSources
      security:
      - openapi_oauth:
        - webinar:read:admin
        - webinar:read
        openapi_authorization: []
      summary: Get webinar tracking sources
      tags:
      - Webinars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--webinars-webinarId-tracking_sources
      x-accepts: application/json
components:
  securitySchemes:
    openapi_authorization:
      in: header
      name: Authorization
      type: apiKey
      x-konfig-globally-required-security: true
    openapi_oauth:
      flows:
        authorizationCode:
          authorizationUrl: /
          refreshUrl: ""
          scopes:
            recording:read:admin: recording:read:admin
            recording:write: recording:write
            recording:write:admin: recording:write:admin
            recording:read: recording:read
            phone_recording:read:admin: phone_recording:read:admin
            device:write:admin: device:write:admin
            device:read:admin: device:read:admin
            h323:write:admin: h323:write:admin
            h323:read:admin: h323:read:admin
            meeting:write: meeting:write
            meeting:write:admin: meeting:write:admin
            meeting:master: meeting:master
            meeting_summary:read:admin: meeting_summary:read:admin
            meeting:read: meeting:read
            meeting:read:admin: meeting:read:admin
            meeting_token:read:admin:live_streaming: meeting_token:read:admin:live_streaming
            meeting_token:read:live_streaming: meeting_token:read:live_streaming
            meeting_token:read:admin:local_archiving: meeting_token:read:admin:local_archiving
            meeting_token:read:local_recording: meeting_token:read:local_recording
            meeting_token:read:admin:local_recording: meeting_token:read:admin:local_recording
            meeting_summary:read: meeting_summary:read
            meeting:write:sip_dialing: meeting:write:sip_dialing
            meeting:write:admin:sip_dialing: meeting:write:admin:sip_dialing
            pac:read:admin: pac:read:admin
            pac:read: pac:read
            report:read:admin: report:read:admin
            sip_phone:write:admin: sip_phone:write:admin
            sip_phone:read:admin: sip_phone:read:admin
            tsp:read:admin: tsp:read:admin
            tsp:write:admin: tsp:write:admin
            tsp:read: tsp:read
            tsp:write: tsp:write
            tracking_fields:write:admin: tracking_fields:write:admin
            tracking_fields:read:admin: tracking_fields:read:admin
            webinar:write: webinar:write
            webinar:write:admin: webinar:write:admin
            webinar:read:admin: webinar:read:admin
            webinar:read: webinar:read
            webinar_token:read:admin:live_streaming: webinar_token:read:admin:live_streaming
            webinar_token:read:live_streaming: webinar_token:read:live_streaming
            webinar_token:read:admin:local_archiving: webinar_token:read:admin:local_archiving
            webinar_token:read:admin:local_recording: webinar_token:read:admin:local_recording
            webinar_token:read:local_recording: webinar_token:read:local_recording
            webinar:write:admin:sip_dialing: webinar:write:admin:sip_dialing
            webinar:write:sip_dialing: webinar:write:sip_dialing
          tokenUrl: ""
      type: oauth2
      x-konfig-globally-required-security: true

